<#
.SYNOPSIS
    Builds (or updates) workbooks/SharePoint mirror.xlsx from power-query/SharePoint mirror/*.pq.

.DESCRIPTION
    Idempotent. Creates the workbook if missing, adds or updates one query per .pq file
    (query name = file base name, same rule as FRM10-12's Sync-PowerQuery.ps1), and loads
    the data queries to one table each on their own sheet. Helper queries (SP_*,
    SyncedFrom) stay connection-only.

    It does NOT refresh - no credentials are needed to build. Refresh with
    Refresh-SharePointMirror.ps1.

.EXAMPLE
    ./Build-SharePointMirror.ps1
#>
param(
    [string]$WorkbookPath = (Join-Path $PSScriptRoot "..\workbooks\SharePoint mirror.xlsx"),
    [string]$QueryPath    = (Join-Path $PSScriptRoot "..\power-query\SharePoint mirror")
)
$ErrorActionPreference = "Stop"

# Loaded to a table, in this sheet order. Everything else in $QueryPath is a helper.
$Loaded = @("Order Items", "Order", "Models", "Model Revisions", "Clients", "Index", "Models SA", "Lists", "VersionCounts", "VersionProbe",
            "Columns", "Order via SharePointTables")

$QueryPath = (Resolve-Path $QueryPath).Path
$files = Get-ChildItem -LiteralPath $QueryPath -Filter *.pq
if ($files.Count -eq 0) { throw "ABORT: no .pq files in $QueryPath" }
foreach ($n in $Loaded) {
    if (-not ($files | Where-Object { $_.BaseName -eq $n })) { throw "ABORT: loaded query '$n' has no .pq file" }
}

$missing = [System.Reflection.Missing]::Value
$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false
try {
    $full = [System.IO.Path]::GetFullPath($WorkbookPath)
    if (Test-Path -LiteralPath $full) {
        $wb = $excel.Workbooks.Open($full)
        Write-Host "opened  $full"
    } else {
        $wb = $excel.Workbooks.Add()
        $readme = $wb.Worksheets.Item(1)
        $readme.Name = "README"
        $readme.Range("A1").Value2 = "SharePoint mirror - generated by scripts/Build-SharePointMirror.ps1. Do not edit tables by hand."
        $readme.Range("A2").Value2 = "Refresh: scripts/Refresh-SharePointMirror.ps1 (writes sharepoint-lists/mirror/*.csv). M source: power-query/SharePoint mirror/."
        $readme.Range("A3").Value2 = "Columns are INTERNAL names; dates are raw REST text (...Z). <Lookup>Id = the id, <Lookup> = its display value."
        $wb.SaveAs($full, 51)   # 51 = xlOpenXMLWorkbook
        Write-Host "created $full"
    }

    # ---- queries
    foreach ($f in $files) {
        $name = $f.BaseName
        $m = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)
        $q = $null
        foreach ($x in $wb.Queries) { if ($x.Name -eq $name) { $q = $x; break } }
        if ($null -eq $q) { $wb.Queries.Add($name, $m) | Out-Null; Write-Host "  query added    $name" }
        elseif ($q.Formula -ne $m) { $q.Formula = $m; Write-Host "  query updated  $name" }
        else { Write-Host "  query same     $name" }
    }

    # ---- one table per loaded query
    foreach ($name in $Loaded) {
        $tbl = "Mirror_" + ($name -replace '[^A-Za-z0-9]', '_')
        $found = $false
        foreach ($ws in $wb.Worksheets) { foreach ($lo in $ws.ListObjects) { if ($lo.Name -eq $tbl) { $found = $true } } }
        if ($found) { Write-Host "  table exists   $tbl"; continue }

        $sheetName = ($name -replace '[\[\]\*\?/\\:]', '_')
        if ($sheetName.Length -gt 31) { $sheetName = $sheetName.Substring(0, 31) }
        $ws = $wb.Worksheets.Add($missing, $wb.Worksheets.Item($wb.Worksheets.Count))
        $ws.Name = $sheetName
        $conn = "OLEDB;Provider=Microsoft.Mashup.OleDb.1;Data Source=`$Workbook`$;Location=`"$name`";Extended Properties=`"`""
        # ListObjects.Add(SourceType=0 xlSrcExternal, Source, LinkSource, XlListObjectHasHeaders=1 xlYes, Destination)
        $lo = $ws.ListObjects.Add(0, $conn, $missing, 1, $ws.Range("A1"))
        $lo.Name = $tbl
        $qt = $lo.QueryTable
        $qt.CommandType = 2        # xlCmdSql
        $qt.CommandText = "SELECT * FROM [$name]"
        $qt.BackgroundQuery = $false
        $qt.RefreshOnFileOpen = $false
        Write-Host "  table added    $tbl  (sheet '$sheetName')"
    }

    $wb.Save()
    Write-Host "saved. Next: Refresh-SharePointMirror.ps1"
}
finally {
    if ($wb) { $wb.Close($false) | Out-Null }
    $excel.Quit()
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) | Out-Null
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
}
