#!/usr/bin/env python3
"""Generate x23_emit_powerfx.js — a console script that EMITS the Power Fx to
paste into the order-creation save, filling each unit's parent columns at the
moment it is created.

Why this is generated, and why it emits rather than states
----------------------------------------------------------
The fix needs 47 target columns and their 47 source fields, written in Power Fx
— which addresses SharePoint by **display name**, not internal name. This repo
has no trustworthy record of either:

  - docs/n3-parent-sync-flow-spec.md names `OrdOrderNumber` / `OrdQty`, neither
    of which exists.
  - docs/lookup-textfield-reference.md names a source field `Model_Revion_ID`
    that does not exist, and carries a warning banner saying so.
  - x21's first run swept `OrderNumber` into the `Ord` group by prefix and
    reported zero gaps.

So: the MAPPING comes from the live flow definitions (what actually runs), and
the DISPLAY NAMES are read off the lists at paste time by the emitted script.
Nothing in the chain is typed from memory.

    python scripts/gen_x23_powerfx.py
"""
import json
import pathlib

import gen_x22_repair as base

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "x23_emit_powerfx.js"

# Which Power Fx variable holds each parent at the moment units are created, and
# the Order Items lookup column that points at it. Read off the save script.
VAR = {
    "Ord": "varNewOrder",
    "Mdl": "SelectedModel",
    "Rev": "SelectedModelRevision",
    "Cli": "SelectedClient",
}


def main():
    mapping = {}
    for fname, (prefix, fk, parent) in base.SOURCES.items():
        guid, raw = base.extract(base.FLOWS / fname)
        fields = []
        for target, tgt_choice, source, src_choice, src_multi in raw:
            if source is None:
                continue
            fields.append({"target": target, "targetChoice": tgt_choice,
                           "source": source, "sourceChoice": src_choice,
                           "sourceMulti": src_multi})
        mapping[prefix] = {"parent": parent, "list": guid, "fk": fk,
                           "var": VAR[prefix], "fields": fields}
        print("%-4s %-16s %2d fields  <- %s" % (prefix, parent, len(fields), VAR[prefix]))

    js = TEMPLATE.replace("__MAPPING__", json.dumps(mapping, indent=2, ensure_ascii=False))
    OUT.write_text(js, encoding="utf-8")

    # 🔴 `Mdl*/Rev*` inside a block comment CLOSES IT. The `*/` is a comment
    # terminator and the rest of the prose becomes code. This has now broken a
    # generated file twice - x21 and x23 - and the symptom is a syntax error
    # pointing at English text, which reads like nonsense. So: check, every time.
    check(js)
    print("\nwrote %s" % OUT.relative_to(HERE.parent))


def check(js):
    """Refuse to ship a file that will not parse. `node --check` when node is
    available; otherwise at least catch the comment-terminator trap."""
    import shutil
    import subprocess

    if shutil.which("node"):
        r = subprocess.run(["node", "--check", str(OUT)], capture_output=True, text=True)
        if r.returncode:
            raise SystemExit("ABORT: emitted file does not parse.\n" + (r.stderr or r.stdout))
        print("  node --check: OK")
        return

    depth, i = 0, 0
    while i < len(js) - 1:
        two = js[i:i + 2]
        if depth == 0 and two == "/*":
            depth, i = 1, i + 2
            continue
        if depth == 1 and two == "*/":
            # A terminator followed by more prose on the same line is the trap.
            rest = js[i + 2:js.find("\n", i) if js.find("\n", i) != -1 else len(js)]
            if rest.strip() and not rest.lstrip().startswith(("\n",)):
                raise SystemExit("ABORT: `*/` mid-comment at offset %d - the `Mdl*/Rev*` trap:\n  %s"
                                 % (i, rest.strip()[:80]))
            depth, i = 0, i + 2
            continue
        i += 1
    print("  comment scan: OK (node not found, so no full parse)")


TEMPLATE = r"""/* X23 -- READ-ONLY. Emits the Power Fx that fixes the race at its source.

   🔴 GENERATED by scripts/gen_x23_powerfx.py from the live N3 flow definitions.
   Do not hand-edit the MAP; re-run the generator after any mapping change.

   HOW TO RUN
     1. Open, signed in:
        https://ermcopower.sharepoint.com/sites/PioneerPlanificatio/_api/web/currentuser
     2. F12 -> Console. Paste this whole file. Press Enter.
     3. Copy the emitted Power Fx into the order-creation save.

   Writes nothing to SharePoint. It only reads column metadata and prints text.

   WHAT IT FIXES
     The save creates the Model Revision, patches Models, then creates the Order
     -- three parent writes about a second apart, each firing its own sync flow
     -- and only then creates the units one at a time at 4-5s each. So:

       - the Order sync fans out into a child list still being written for
         roughly Qty x 4.5 seconds  ->  THE RACE (order 22169 lost 4 of 10);
       - three flows fan out onto the same rows within one second
         ->  SAVE CONFLICT 400, never retried (22172, 22175).

     Both vanish if the unit is born complete. At the moment it creates each
     unit the app already holds varNewOrder, SelectedModel,
     SelectedModelRevision and SelectedClient -- every value the flows would
     write. One writer, at a moment when no other writer exists.

     It also retires the post-backfill gap: a unit created at any time is right.

   ⚠️ WHY THE NAMES ARE READ AND NOT TYPED
     Power Fx addresses SharePoint by DISPLAY name; the flows use INTERNAL
     names. This repo's docs have named non-existent fields three times
     (`OrdOrderNumber`, `OrdQty`, `Model_Revion_ID`). So the mapping below comes
     from the flow definitions, and the display names are read off the live
     lists right here, by _api/v2.0/.../columns -- the one route that works on
     this tenant (_api/web/lists/.../fields hangs: four 45-second timeouts).

   ⚠️ WHAT THIS DOES NOT DO
     The N3 flows still exist and still handle LATER parent edits, where two of
     them can still collide on one row. The retry scope is still worth adding.
     This takes order creation -- the common path -- off the collision course.
*/
(async () => {
  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const OI   = "d6468ec5-c7b5-44a3-8ce0-f81f059b671d";

  const MAP = __MAPPING__;

  const J = async (u) => {
    const r = await fetch(u, { credentials: "include",
      headers: { Accept: "application/json;odata=nometadata" } });
    if (!r.ok) throw new Error(r.status + " " + r.statusText);
    return r.json();
  };
  const cols = async (guid) => {
    const j = await J(base + "/_api/v2.0/sites/root/lists/" + guid + "/columns");
    const by = {};
    for (const c of (j.value || [])) by[c.name] = c;
    return by;
  };

  const target = await cols(OI);
  if (!Object.keys(target).length) { console.error("ABORT: read 0 columns on Order Items."); return; }

  /* A display name containing a quote would break the emitted Power Fx. Power
     Fx escapes a single quote by doubling it. */
  const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

  const lines = { Ord: [], Mdl: [], Rev: [], Cli: [] };
  const problems = [];

  for (const g of Object.keys(MAP)) {
    const m = MAP[g];
    const src = await cols(m.list);
    if (!Object.keys(src).length) { problems.push(g + ": could not read " + m.parent + " columns"); continue; }

    for (const f of m.fields) {
      const t = target[f.target], s = src[f.source];
      if (!t) { problems.push(f.target + " is not a column on Order Items"); continue; }
      if (!s) { problems.push(f.source + " is not a column on " + m.parent
                  + " (target " + f.target + ")"); continue; }

      const ref = m.var + "." + q(s.displayName);
      let expr;

      if (f.sourceMulti) {
        /* MultiChoice source, single-value target. The flow does
           first(...)?['Value']; First(...).Value is the Power Fx equivalent.
           Matching the flow matters more than improving on it -- otherwise
           app-created rows and flow-synced rows disagree. */
        expr = "First(" + ref + ").Value";
      } else if (t.choice) {
        /* A Choice TARGET takes a record. If the source is also a Choice or a
           Lookup it already is one, so pass it straight through. */
        expr = (s.choice || s.lookup) ? ref : "{ Value: " + ref + " }";
      } else if (s.lookup) {
        /* Lookup source into a text target: take the displayed value. This is
           the set x22 silently skipped -- MdlLatestModelRevision,
           MdlParentModel, RevDuplicateOrder, RevPioneerModelCode. */
        expr = ref + ".Value";
      } else if (s.choice) {
        expr = ref + ".Value";
      } else {
        expr = ref;
      }

      lines[g].push({ name: q(t.displayName), expr: expr });
    }
  }

  /* `swap` rewrites a group's source variable for the SA branch, and `guard`
     wraps it so a missing twin writes nothing.

     🔑 THE ZERO-MATCH RULE, and why the guard is not optional. 15 of 390 models
     have an SA twin -- 96% do not. `If()` with no else returns Blank(), so a
     twinless SA unit gets blank Mdl* / Rev*, which is correct and is exactly what
     the existing `Model:` / `'Model Revision':` lines in the save already do.
     Writing the MAIN model's values there instead is the failure the N3 spec's
     zero-match branch exists to prevent. */
  const render = (g, swap, guard) => lines[g].map(l => {
    let e = l.expr;
    if (swap) for (const from of Object.keys(swap))
      e = e.split(from + ".").join(swap[from] + ".").split("(" + from + ")").join("(" + swap[from] + ")");
    if (guard) e = "If(!IsBlank(SelectedSAModel), " + e + ")";
    return "        " + l.name + ": " + e;
  }).join(",\n");

  const block = (groups, swap, guardGroups) => groups
    .map(g => "        // --- " + MAP[g].parent + " (" + lines[g].length + " fields)"
              + ((guardGroups || []).indexOf(g) >= 0 ? ", SA twin, blank when there is none" : "") + " ---\n"
              + render(g, (guardGroups || []).indexOf(g) >= 0 ? swap : null,
                          (guardGroups || []).indexOf(g) >= 0))
    .join(",\n");

  console.log("=== 1. paste into the MAIN unit Patch, after 'Model Revision' ===\n");
  console.log(",\n" + block(["Ord", "Mdl", "Rev", "Cli"]));

  console.log("\n\n=== 2. resolve the SA twin's revision row ===");
  console.log("SelectedSAModel holds the twin MODEL, but its revision is only a lookup, so the");
  console.log("Rev* fields have nothing to read. Add this beside the existing SelectedSAModel");
  console.log("Set(), inside the same If(varNewOrder.SA, ...) block:\n");
  console.log("    Set(");
  console.log("        SelectedSAModelRevision,");
  console.log("        LookUp('Model Revisions', ID = SelectedSAModel.'Latest Model Revision'.Id)");
  console.log("    );");
  console.log("\n    // LookUp on a blank SelectedSAModel returns blank, which the guards below expect.");

  console.log("\n\n=== 3. paste into the SA unit Patch, after 'Model Revision' ===\n");
  console.log(",\n" + block(["Ord", "Mdl", "Rev", "Cli"],
                            { "SelectedModel": "SelectedSAModel",
                              "SelectedModelRevision": "SelectedSAModelRevision" },
                            ["Mdl", "Rev"]));
  console.log("\n        // Ord*/Cli* are order-level and client-level, so an SA unit takes the");
  console.log("        // same values as its non-SA siblings -- unguarded, above.");
  console.log("        // Mdl*/Rev* come from the TWIN and are guarded: 15 of 390 models have one.");

  console.log("\n\n=== check before pasting ===");
  const n = lines.Ord.length + lines.Mdl.length + lines.Rev.length + lines.Cli.length;
  console.log("  fields emitted: Ord " + lines.Ord.length + "  Mdl " + lines.Mdl.length
    + "  Rev " + lines.Rev.length + "  Cli " + lines.Cli.length
    + "   total " + n + " per unit, on both the main and the SA Patch");
  if (problems.length) {
    console.log("  🔴 " + problems.length + " unresolved -- do NOT paste until these are understood:");
    for (const p of problems) console.log("      " + p);
  } else {
    console.log("  ✅ every mapped field resolved to a real column on both sides.");
  }
  console.log("\n  ⚠️ CliLeadTimeWeeks: the Clients sync flow reads `body/CliLeadTimeWeeks`,");
  console.log("     which is its own DESTINATION column name, not a field on Clients. The");
  console.log("     line emitted above uses whatever that resolves to -- if Cli shows 0");
  console.log("     fields or appears in the problem list, that is the bug, not this script.");
  console.log("  ⚠️ Dates: Power Fx sends a date value, not a string. The UTC-midnight trap");
  console.log("     that bit the backfill applies to raw REST writes, not to this path.");
  console.log("  ⚠️ Test on a ONE-unit order first, then a 10-unit one, and re-run");
  console.log("     x19_parent_history_probe.js against it: sibling divergence must be none.");
})();
"""

if __name__ == "__main__":
    main()
