# -*- coding: utf-8 -*-
"""N3 -- the parent sync flow spec, written so building it is mechanical.
Mapping tables come from the N2 field definitions, so source and target names
match what N2 actually creates."""
import json, io, collections

WA = r"C:\Users\solei\OneDrive\Documents\Biplan\claude\Clients\Pioneer Transformer\Workflow-Automation"
OUT = WA + r"\docs\n3-parent-sync-flow-spec.md"
fields = json.load(io.open(WA + r"\sharepoint-lists\N2 field definitions 2026-09-05.json", encoding="utf-8"))

by = collections.defaultdict(list)
for f in fields:
    by[f["list"]].append(f)

FLOWS = [
    ("Order", "Order", "Order Items - sync from Order", 3.1, 29),
    ("Models", "Models", "Order Items - sync from Models", 6.9, 91),
    ("Model Revisions", "Model Revisions", "Order Items - sync from Model Revisions", 2.6, None),
]

L = []; a = L.append
a("# N3 — the parent sync flows, build spec")
a("")
a("Generated 2026-09-05 (`scripts/gen_n3.py`). Mapping tables come straight from the N2 field")
a("definitions, so every target name here is exactly what `n2_create_columns.js` creates.")
a("")
a("**Prerequisites:** N2 (the 48 columns exist) and **A3** (2c stage-stamping stripped out of the")
a("`Order Items` trigger flow). A3 is not optional — see *Capacity* below.")
a("")
a("## 🔴 Read the lookup internal names before you build")
a("")
a("The fan-out filter needs the internal name of each lookup **on `Order Items`** — the columns")
a("pointing back at `Order`, `Models` and `Model Revisions`. **I could not read them.** They are")
a("absent from the list export's `ListSchema` record entirely, and the tenant timed out on the REST")
a("call. So they are deliberately left as placeholders below rather than guessed.")
a("")
a("Run this first and substitute the real values:")
a("")
a("```")
a("/_api/web/lists/getbytitle('Order Items')/fields")
a("   ?$select=Title,InternalName,TypeAsString,LookupList,LookupField")
a("   &$filter=TypeAsString eq 'Lookup'")
a("```")
a("")
a("This is the same rule as everywhere else in this repo: a retyped internal name writes nothing,")
a("silently. `Protector & Switchgear Item #` on this very list is `Protector_x0020__x0026__x0020_Sw`,")
a("truncated mid-word at 32 characters.")
a("")
a("## Shape — the same five blocks in each flow")
a("")
a("```")
a("1  Trigger      When an item is created or modified   (the parent list)")
a("2  Guard        Trigger condition -- skip our own writes")
a("3  Fan out      Get items on Order Items, Filter Query on the lookup Id")
a("4  Apply to each")
a("     4a  Compose  needsUpdate   -- OR of per-field comparisons")
a("     4b  Condition needsUpdate is true")
a("           Update item  (one call, all changed fields)")
a("5  (Order/Models only)  the SA branch -- see below")
a("```")
a("")
a("### 2 — the trigger condition matters more than it looks")
a("")
a("A sync flow that writes to `Order Items` does not re-trigger *itself*, but it **does** fire the")
a("`Order Items` create-or-update trigger flow once per row written. Put a **trigger condition** on")
a("that flow so a sync-only write never creates a run — conditions are evaluated *before* a run")
a("exists, so they cost nothing. A first-action Condition does not help: the run is already charged.")
a("")
a("### 3 — the fan-out filter")
a("")
a("```")
a("Get items")
a("  Site / List:   Order Items")
a("  Filter Query:  <LookupInternalName>Id eq @{triggerOutputs()?['body/ID']}")
a("  Top Count:     5000")
a("  Pagination:    on, threshold 5000")
a("```")
a("")
a("Filter on the lookup's `Id`, not on a `_TextField` mirror. The mirrors are stale — their sync")
a("flows have been off since Aug 21 — so filtering on them would silently miss rows.")
a("")
a("### 4a — the change-guard is mandatory, not an optimisation")
a("")
a("Without it, one edit to a `Models` row rewrites every unit using that model, and each of those")
a("writes fires the trigger flow. Build one `Compose` per flow that ORs the comparisons:")
a("")
a("```")
a("@or(")
a("  not(equals(coalesce(items('Apply_to_each')?['<target>'], ''),")
a("             coalesce(triggerOutputs()?['body/<source>'], ''))),")
a("  ...one line per column...")
a(")")
a("```")
a("")
a("`coalesce(..., '')` on both sides matters: `null` and `''` are not equal in Power Automate, so")
a("without it every row with a blank looks changed and the guard never fires.")
a("")

for lst, _src, name, avg, worst in FLOWS:
    cols = by.get(lst, [])
    a("## `%s`" % name)
    a("")
    a("Trigger list **`%s`** · **%d columns** · fan-out avg **%.1f**%s" %
      (lst, len(cols), avg, (", worst **%d**" % worst) if worst else ""))
    a("")
    a("| Source column | → `Order Items` column | Internal name | Type |")
    a("|---|---|---|---|")
    for f in sorted(cols, key=lambda x: x["display"]):
        a("| `%s` | `%s` | `%s` | %s%s |" % (
            f["srcCol"], f["display"], f["name"], f["type"],
            " ⚠️ was %s" % f["srcType"] if f["type"] != f["srcType"] else ""))
    a("")

a("## 🔴 The SA branch — `Model` and `Model Revision` are not in the tables above")
a("")
a("Those two are **not** prefixed columns. They overwrite the existing `Order Items.Model` and")
a("`Order Items.Model Revision` lookups, by decision: a model corrected on the `Order` must reach")
a("every unit of that order. That makes them the one destructive write in this whole design.")
a("")
a("Inside the `Apply to each`, before writing either:")
a("")
a("```")
a("Condition:  items('Apply_to_each')?['SAJob']  is equal to  false")
a("")
a("  YES ->  write Order.Model straight through")
a("")
a("  NO  ->  resolve the twin:")
a("            Get items on Models")
a("              Filter Query:  SA_x0020_Model eq 1")
a("                         and Parent_x0020_Model eq '<new model's Model_Code>'")
a("            if exactly one match  -> write it")
a("            if zero matches       -> DO NOT WRITE. Flag for engineering.")
a("```")
a("")
a("Measured 2026-09-05, and this is why the branch exists:")
a("")
a("| | |")
a("|---|---|")
a("| Orders holding both an SA and a non-SA unit, model known on both | **34** |")
a("| …where the SA unit carries a **different** model | **32** |")
a("| Orders where non-SA siblings disagree | **0** |")
a("| SA models where `Parent Model` resolves correctly | **15 of 15** |")
a("| Models that have a twin **at all** | **15 of 390** |")
a("")
a("So the zero-match branch is not an edge case — **96% of models have no twin**. Writing a blank or")
a("the main model there is exactly the failure this guard exists to prevent.")
a("")
a("**Five SA units already sit on plain `M-` models** (`22098-1/1 SA`, `22099-1/1 SA`,")
a("`22107-1/1 SA`, `22108-1/1 SA`, `22110-1/1 SA`) and one has no model at all")
a("(`21499-1/3 SA`). Resolve those by hand *before* the flow runs, or they take the zero-match")
a("branch on the first edit.")
a("")
a("## `Models` → SA twin — the self-edge")
a("")
a("A change to a model must also reach its SA twin, so this flow writes **`Models` → `Models`**.")
a("Editing `M-HYQU-0092` fires it, it writes `MSA-HYQU-0092`, and that fires it again. It terminates")
a("today only because no `MSA-` model has a twin of its own — luck, not design.")
a("")
a("Two guards, both cheap:")
a("")
a("1. The change-guard above — nothing is written when nothing differs, so the second hop stops.")
a("2. **Skip outright when `SA Model` is already true.** A twin can then never trigger another hop,")
a("   regardless of what the change-guard does.")
a("")
a("## `Clients.Lead Time` → `Order Items`")
a("")
a("One column, and it is the exception to *don't sync Clients*. Same shape as the flows above.")
a("")
a("⚠️ **Fan-out is 27.5 average and 698 worst** — HYDRO QUEBEC is 68% of the list. That is fine")
a("*after* A3 (~5 actions per trigger run, drains in minutes) and is the load shape that hit the")
a("capacity cap *before* it. **Build it now, enable it after A3.**")
a("")
a("`Pièce critique` and `Fournisseur` do **not** travel — reference data, one lookup away.")
a("")
a("## Capacity — why A3 comes first")
a("")
a("| Parent | Rows | Avg fan-out | Worst |")
a("|---|---|---|---|")
a("| `Order` | 445 | 3.1 | 29 |")
a("| `Models` | 390 | 6.9 | 91 |")
a("| `Model Revisions` | 391 | ~2.6 | not measured |")
a("| `Clients` | 98 | 27.5 | **698** |")
a("")
a("Each written row fires the `Order Items` trigger flow. At its current ~100 actions that is the")
a("load that wedged 29+ instances on Sep 2. After A3 it is ~5 actions. **The change-guard and the")
a("trigger condition together are what make this safe** — the guard stops unnecessary writes, the")
a("condition stops the necessary ones from costing a run.")
a("")
a("## Build order")
a("")
a("1. Read the lookup internal names (top of this doc).")
a("2. `Model Revisions` first — 24 columns, smallest fan-out, no SA branch. Proves the pattern.")
a("3. `Models` — 4 columns, plus the self-edge guards.")
a("4. `Order` — 19 columns, plus the SA branch. The riskiest, built last on a proven pattern.")
a("5. `Clients.Lead Time` — after A3.")
a("")
a("Test each on **one** parent row with a small fan-out before enabling. `Order` is the natural")
a("choice: pick an order with 2–3 units and no SA.")

io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote n3-parent-sync-flow-spec.md")
for lst, _s, name, _a, _w in FLOWS:
    print("  %-18s %d columns" % (lst, len(by.get(lst, []))))
print("  total mapped:", sum(len(by[k]) for k, *_ in [(f[0],) for f in FLOWS]))
