#!/usr/bin/env python3
"""Generate power-query/SharePoint mirror/SyncedFrom.pq from the LIVE N3 flow definitions.

The mirror workbook's `Columns` table says, for every Order Items column a flow
writes, which parent list and field it is copied from and by which flow. That map
must never be hand-typed - two docs already carry wrong source names (see the
header of gen_x22_repair.py) - so this reuses gen_x22_repair's own extractor over
workflow-data/n3-flows/, the same source x22 writes from.

Re-run after any N3 mapping change, then push the .pq with Sync-PowerQuery.ps1
(or Build-SharePointMirror.ps1) and refresh.

    python scripts/gen_mirror_synced_from.py
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import gen_x22_repair as g  # noqa: E402  (extract, SOURCES, FLOWS)

OUT = HERE.parent / "power-query" / "SharePoint mirror" / "SyncedFrom.pq"


def m_text(s):
    return "null" if s is None else '"' + str(s).replace('"', '""') + '"'


def main():
    rows = []
    for fname, (prefix, fk, parent) in g.SOURCES.items():
        path = g.FLOWS / fname
        if not path.exists():
            raise SystemExit("ABORT: missing %s" % path)
        flow = fname.replace(".definition.json", "").replace("__", " - ").replace("_", " ")
        _, raw = g.extract(path)
        for target, tgt_choice, source, src_choice, src_multi in raw:
            if source is None:
                read = "constant (not from the parent row)"
            elif src_multi:
                read = "first(...)?['Value'] of a MultiChoice"
            elif src_choice:
                read = "?['Value'] (Choice/lookup)"
            else:
                read = "plain"
            rows.append((target, parent, source, flow, fk, read))
    if not rows:
        raise SystemExit("ABORT: extracted 0 mappings - a zero-row read is a failed read.")

    lines = ",\n        ".join(
        "{" + ", ".join(m_text(v) for v in ("Order Items",) + r) + "}" for r in rows)
    m = (
        "// GENERATED by scripts/gen_mirror_synced_from.py from workflow-data/n3-flows/.\n"
        "// Do not hand-edit: re-run the generator after any N3 mapping change.\n"
        "// One row per Order Items column an N3 sync flow writes.\n"
        "#table(\n"
        "    type table [list = text, internalName = text, syncedFromList = text, syncedFromField = text,\n"
        "                syncedByFlow = text, viaLookup = text, readAs = text],\n"
        "    {\n        " + lines + "\n    }\n)\n")
    OUT.write_text(m, encoding="utf-8")
    print("wrote %s  (%d mappings)" % (OUT.relative_to(HERE.parent), len(rows)))


if __name__ == "__main__":
    main()
