# -*- coding: utf-8 -*-
"""Emit a browser-console script that creates the 48 N2 columns.

I cannot run this myself -- the scripted write to SharePoint is blocked by a
permission boundary, which is correct and not something to route around. So the
work is handed over as something the user runs, with the field definitions
already verified against the picker and the internal names already chosen.
"""
import json, io

fields = json.load(io.open("n2_fields.json", encoding="utf-8"))
OUT = (r"C:\Users\solei\OneDrive\Documents\Biplan\claude\Clients\Pioneer Transformer"
       r"\Workflow-Automation\scripts\n2_create_columns.js")

L = []; a = L.append
a("/* N2 -- create the %d parent-sync columns on Order Items." % len(fields))
a("")
a("   HOW TO RUN")
a("     1. Open the site in the browser, signed in:")
a("        https://ermcopower.sharepoint.com/sites/PioneerPlanificatio")
a("     2. F12 -> Console. Paste this whole file. Press Enter.")
a("     3. It prints a per-field result, then reads every field back and prints")
a("        what SharePoint actually stored. Trust the read-back, not the POSTs.")
a("")
a("   WHAT IT DOES")
a("     Creates each column with createfieldasxml and Options: 8")
a("     (AddFieldInternalNameHint), which makes SharePoint honour the Name")
a("     attribute as the internal name instead of deriving it from DisplayName.")
a("     That is what avoids the create-short-then-rename dance AND the")
a("     32-character truncation -- Protector & Switchgear Item # on this same")
a("     list already became Protector_x0020__x0026__x0020_Sw, stopping mid-word.")
a("")
a("     Options deliberately does NOT include 16 (AddFieldToDefaultView).")
a("     Dropping %d columns into the default view would wreck it." % len(fields))
a("")
a("     Every column lands in the group 'Parent Sync', so they are easy to find")
a("     and easy to remove -- see UNDO at the bottom.")
a("")
a("   TYPES ARE REMAPPED ON PURPOSE, not copied from the source list:")
a("     DateTime    -> DateOnly   copying DateTime reintroduces the UTC-midnight")
a("                               bug the whole backfill exists to fix")
a("     Choice      -> Text       a synced Choice silently REJECTS any value")
a("                               outside its option list, per row, inside the")
a("                               sync flow -- the Family failure mode. The")
a("                               source list already enforces the domain.")
a("     Lookup      -> Text       a lookup ID is meaningless across lists;")
a("                               sync the display value")
a("     MultiChoice -> Note       exports as a JSON array, can be long")
a("")
a("   These are all EMPTY columns. Creating them changes no data and fires no")
a("   flow. The sync flows (N3) are a separate step and wait for A3.")
a("*/")
a("")
a("(async () => {")
a('  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";')
a('  const LIST = "Order Items";')
a("")
a("  const FIELDS = [")
for f in fields:
    a('    %s,' % json.dumps(f["xml"]))
a("  ];")
a("")
a("  const dg = await (await fetch(base + \"/_api/contextinfo\", {")
a('    method: "POST", credentials: "include",')
a('    headers: { "Accept": "application/json;odata=nometadata" }')
a("  })).json();")
a("  const digest = dg.FormDigestValue;")
a("")
a("  const results = [];")
a("  for (const xml of FIELDS) {")
a('    const disp = (xml.match(/DisplayName="([^"]*)"/) || [])[1];')
a("    try {")
a('      const r = await fetch(base + "/_api/web/lists/getbytitle(\'" + LIST + "\')/fields/createfieldasxml", {')
a('        method: "POST", credentials: "include",')
a("        headers: {")
a('          "Accept": "application/json;odata=nometadata",')
a('          "Content-Type": "application/json;odata=verbose",')
a('          "X-RequestDigest": digest')
a("        },")
a("        body: JSON.stringify({ parameters: {")
a('          __metadata: { type: "SP.XmlSchemaFieldCreationInformation" },')
a("          SchemaXml: xml, Options: 8 } })")
a("      });")
a('      results.push({ field: disp, ok: r.ok, status: r.status,')
a('                     error: r.ok ? "" : (await r.text()).slice(0, 200) });')
a("    } catch (e) {")
a('      results.push({ field: disp, ok: false, status: 0, error: String(e) });')
a("    }")
a("  }")
a("")
a('  console.table(results);')
a('  const bad = results.filter(x => !x.ok);')
a('  console.log(bad.length ? "FAILED: " + bad.length + " of " + results.length')
a('                         : "all " + results.length + " posted OK");')
a("")
a("  // Read back what SharePoint actually stored. A POST returning 200 is not")
a("  // proof the field is the type you asked for.")
a('  const v = await (await fetch(base + "/_api/web/lists/getbytitle(\'" + LIST +')
a('    "\')/fields?$select=Title,InternalName,TypeAsString&$filter=Group%20eq%20\'Parent%20Sync\'",')
a('    { credentials: "include", headers: { "Accept": "application/json;odata=nometadata" } })).json();')
a('  console.log("stored in group \'Parent Sync\': " + v.value.length + " (expect %d)");' % len(fields))
a("  console.table(v.value);")
a("})();")
a("")
a("")
a("/* ---------------------------------------------------------------- UNDO --")
a("   Deletes every column in the 'Parent Sync' group. Safe while they are")
a("   empty; once the sync flows have written data this destroys it.")
a("")
a("(async () => {")
a('  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";')
a('  const LIST = "Order Items";')
a('  const dg = await (await fetch(base + "/_api/contextinfo", { method: "POST",')
a('    credentials: "include", headers: { "Accept": "application/json;odata=nometadata" } })).json();')
a('  const v = await (await fetch(base + "/_api/web/lists/getbytitle(\'" + LIST +')
a('    "\')/fields?$select=InternalName&$filter=Group%20eq%20\'Parent%20Sync\'",')
a('    { credentials: "include", headers: { "Accept": "application/json;odata=nometadata" } })).json();')
a("  for (const f of v.value) {")
a('    await fetch(base + "/_api/web/lists/getbytitle(\'" + LIST +')
a('      "\')/fields/getbyinternalnameortitle(\'" + f.InternalName + "\')", {')
a('      method: "POST", credentials: "include",')
a('      headers: { "X-RequestDigest": dg.FormDigestValue, "X-HTTP-Method": "DELETE",')
a('                 "IF-MATCH": "*" } });')
a('    console.log("deleted " + f.InternalName);')
a("  }")
a("})();")
a("---------------------------------------------------------------------- */")

io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote scripts/n2_create_columns.js  (%d fields)" % len(fields))
