# -*- coding: utf-8 -*-
"""Generate scripts/x25_parent_drift_scan.js -- the whole-list version of x7.

    python scripts/gen_x25_drift_scan.py

The field map is lifted verbatim out of x7_verify_parent_sync.js (itself generated from
the N3 flow definitions by gen_x7_verifier.py), so the per-unit and whole-list checks can
never disagree about what is mapped. Re-run this after gen_x7_verifier.py.
"""
import io, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
X7 = os.path.join(HERE, "x7_verify_parent_sync.js")
OUT = os.path.join(HERE, "x25_parent_drift_scan.js")

src = io.open(X7, encoding="utf-8").read()
m = re.search(r"^  const PARENT = \{.*?^  \};\n  const MAP = \{.*?^  \};\n", src, re.S | re.M)
assert m, "could not find PARENT/MAP in x7 -- has its layout changed?"
maps = m.group(0)
n_fields = len(re.findall(r'^\s*"(plain|choice|lookup|multichoice|url)"\s*$', maps, re.M))
assert n_fields == 46, "x7 maps %d fields, expected 46 -- re-check before trusting" % n_fields

HEAD = r'''/* X25 -- READ-ONLY. Which units hold parent data that no longer matches the parent?

   🔴 GENERATED by scripts/gen_x25_drift_scan.py from x7_verify_parent_sync.js. Do not
   hand-edit PARENT/MAP -- re-run the generator.

   HOW TO RUN
     Open https://ermcopower.sharepoint.com/sites/PioneerPlanificatio/_api/web/currentuser
     signed in, F12 -> Console, paste this whole file, Enter. Writes nothing.

   WHY
     x7 answers this for ONE unit, x21 only finds units whose parent columns are wholly
     EMPTY, and x22 only fills blanks. None of them sees a unit that holds an OLD value --
     which is exactly what a day of N3 flows not running leaves behind (2026-09-24, the
     password reset): staff edited Orders/Models/Revisions, the flows never fanned out,
     and every child of those parents still carries the pre-edit value.

   HOW IT COMPARES -- identical to x7, on purpose
     Same map, same normalisation, lookups read through FieldValuesAsText (a plain item
     read omits lookup fields entirely, and $expand=X/Title returns null here -- x7's
     first version reported false mismatches that way). A mismatch here is a mismatch x7
     would report on that unit.

   READING THE RESULT
     Each drifted parent row is printed with its own `Modified`. Rows modified SINCE
     (below) are the ones the outage explains; older ones are pre-existing drift -- expect
     MdlLatestModelRevision list-wide (docs/n3-fanout-race-2026-09-21.md, parked item 2).
     Clients is not scanned: its flow reads the wrong field (parked item 4).
*/
(async () => {
  const SINCE = "2026-09-24T00:00:00-04:00";   // <-- start of the outage, Eastern
  const CONC  = 6;
  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const OI   = "d6468ec5-c7b5-44a3-8ce0-f81f059b671d";
'''

BODY = r'''
  const H = {Accept:"application/json;odata=nometadata"};
  const J = async u => { const r = await fetch(u, {credentials:"include", headers:H});
    if (!r.ok) throw new Error(r.status + " on " + u.slice(0,160) + " :: " + (await r.text()).slice(0,200));
    return r.json(); };
  const page = async (u) => { let o=[],g=0;
    while (u && g++<40){ const j=await J(u); o=o.concat(j.value||[]); u=j["odata.nextLink"]||null; } return o; };
  const pool = async (xs, f) => { for (let i=0;i<xs.length;i+=CONC) await Promise.all(xs.slice(i,i+CONC).map(f)); };

  // x7's normalisation, verbatim in effect.
  const norm = v => {
    if (v === null || v === undefined) return "";
    if (typeof v === "object") return JSON.stringify(v);
    return String(v).trim();
  };
  const flat = v => {
    if (Array.isArray(v)) return v.map(x => (x && x.Value !== undefined) ? x.Value : x).join("; ");
    if (v && typeof v === "object") return v.Value !== undefined ? v.Value : (v.Url !== undefined ? v.Url : v);
    return v;
  };
  const since = new Date(SINCE);

  // ------------------------------------------------------------------ units
  const fks = Object.values(PARENT).map(p => p.fk);
  const tgts = [].concat(...Object.values(MAP).map(fs => fs.map(f => f[0])));
  const units = await page(base + "/_api/web/lists(guid'" + OI + "')/items?$select="
                           + ["Id","Title"].concat(fks, tgts).join(",") + "&$top=500");
  if (!units.length) { console.error("ABORT: read 0 units. A zero-row read is a failed read."); return; }
  console.log("units read: " + units.length);

  const report = [];            // one row per (unit, field) mismatch
  const perParent = {};         // "list#id" -> {list, id, modified, units:Set, fields:Set}

  for (const pname of Object.keys(MAP)) {
    const p = PARENT[pname], fields = MAP[pname];
    const plain = fields.filter(f => f[2] !== "lookup").map(f => f[1]);
    const rows = await page(base + "/_api/web/lists(guid'" + p.id + "')/items?$select="
                            + ["Id","Modified"].concat(plain).join(",") + "&$top=500");
    if (!rows.length) { console.error("ABORT: read 0 rows from " + pname); return; }
    const byId = new Map(rows.map(r => [r.Id, r]));

    // Lookups: FieldValuesAsText, but only for parents some unit actually points at.
    const used = [...new Set(units.map(u => u[p.fk]).filter(x => x != null))];
    const txt = new Map();
    if (fields.some(f => f[2] === "lookup")) {
      let failed = 0;
      await pool(used, async id => {
        try { txt.set(id, await J(base + "/_api/web/lists(guid'" + p.id + "')/items(" + id + ")/FieldValuesAsText")); }
        catch (e) { failed++; }
      });
      if (failed) console.warn(pname + ": FieldValuesAsText failed on " + failed + " rows -- their lookup fields are NOT checked");
    }
    console.log(pname + ": " + rows.length + " rows, " + used.length + " linked");

    let n = 0;
    for (const u of units) {
      const pid = u[p.fk];
      if (pid == null) continue;
      const par = byId.get(pid);
      if (!par) { report.push({unit:u.Title, list:pname, field:"(parent " + pid + " missing)", unitV:"", parentV:"", modified:""}); continue; }
      for (const [tgt, src, kind] of fields) {
        let pv;
        if (kind === "lookup") { const t = txt.get(pid); if (!t) continue; pv = t[src]; }
        else pv = flat(par[src]);
        const a = norm(flat(u[tgt])), b = norm(pv);
        if (a === b) continue;
        n++;
        report.push({unit:u.Title, list:pname, field:tgt, unitV:a.slice(0,40), parentV:b.slice(0,40),
                     modified:par.Modified, recent:new Date(par.Modified) >= since});
        const k = pname + "#" + pid;
        (perParent[k] = perParent[k] || {list:pname, id:pid, modified:par.Modified,
          recent:new Date(par.Modified) >= since, units:new Set(), fields:new Set()});
        perParent[k].units.add(u.Title); perParent[k].fields.add(tgt);
      }
    }
    console.log("   mismatched unit-fields: " + n);
  }

  // ------------------------------------------------------------------ summary
  const byField = {};
  for (const r of report) { const k = r.list + " . " + r.field;
    byField[k] = byField[k] || {recent:0, older:0}; byField[k][r.recent ? "recent" : "older"]++; }
  console.log("\n=== mismatches by field  (recent = parent modified since " + SINCE + ") ===");
  console.table(Object.entries(byField).sort((a,b) => (b[1].recent+b[1].older)-(a[1].recent+a[1].older))
    .map(([k,v]) => ({field:k, recent:v.recent, older:v.older})));

  const parents = Object.values(perParent).sort((a,b) => (b.recent - a.recent) || (a.modified < b.modified ? 1 : -1));
  const recent = parents.filter(p => p.recent);
  console.log("\n=== drifted parent rows modified since " + SINCE + ": " + recent.length + " ===");
  console.table(recent.map(p => ({list:p.list, id:p.id, modified:p.modified, units:p.units.size,
    fields:[...p.fields].join(", ").slice(0,80)})));
  console.log("older drifted parent rows: " + (parents.length - recent.length));

  console.log("\nunits affected in total: " + new Set(report.map(r => r.unit)).size
              + "   unit-field mismatches: " + report.length);
  console.log("full detail: copy(window.x25) puts every row on the clipboard as JSON");
  window.x25 = {report, parents: parents.map(p => ({...p, units:[...p.units], fields:[...p.fields]}))};
})();
'''

io.open(OUT, "w", encoding="utf-8").write(HEAD + maps + BODY)
print("wrote %s  (%d mapped fields from x7)" % (OUT, n_fields))
