/* N5 -- put the client lead times on the Clients list, and add the one column
   Order Items needs to compute dates from them.

   GENERATED by scripts/gen_n5_lead_times.py from reports/frm13-leedtime.json.
   Edit the template (_n5_template.js), never this file.

   HOW TO RUN
     1. Open, signed in:
        https://ermcopower.sharepoint.com/sites/PioneerPlanificatio/_api/web/currentuser
     2. F12 -> Console. Paste this whole file. Press Enter.
     3. DRY RUN by default. Read the plan, then set APPLY = true and paste again.
     4. It prints an UNDO block and re-reads everything it wrote.

   RUN THIS AFTER CUTOVER. It adds a column to Order Items, and until the transfer
   flow is deleted that flow proves 130 field names on every run. Adding columns
   underneath a live flow is the class of change this project keeps for a quiet
   window.

   WHY
     Client lead times exist in exactly one place today: the LeedTime table on
     sheet DelaisApproParClients in FRM13 (A6:H24, 18 rows). FRM10-12 pulls it in
     as ClientLeadTimes, and two things depend on it:

       Ing. Due Date            base - (leadWeeks + 4) * 7 days
                                base = Tanking End Date, else Initial Promised Date

       Estimated Delivery Date  branch 7, read out of the workbook 2026-09-10:
                                Order Date + 90 + XLOOKUP(Client, ..., 52) * 7

     Note the 52 in that XLOOKUP. FRM13's own GENERIC VALUE row says 26. The two
     disagree and always have; whichever is right has to be settled in both places.
     This script seeds the real per-client values and does not touch the default --
     it is not the place to decide that.

     And Order.Lead Time is NOT this value. Measured 2026-09-05: of the 342 orders
     whose client appears in LeedTime, 306 disagree. It is mostly the SharePoint
     column default of 26 with occasional hand edits -- a per-order override, not
     the client's lead time. Do not feed it into these formulas.

   THE DATA
     17 clients plus a generic default of 26 weeks, read out of FRM13 on
     2026-09-10 rather than typed. 15 match the Clients list exactly; two do not
     and carry an explicit alias, resolved against the Order list:

       CITY OF RED DEER  ->  RED DEER      (REDE)    1 order
       HYDRO OTTAWA      ->  OTTAWA HYDRO  (OTHY)   15 orders

     The section sign appears in both sources where an ampersand belongs (LG§E,
     PSE§G, MADISON GAS § ELECTRIC), so those match as they are. Left alone
     deliberately: fixing that encoding is a separate change, and doing it here
     would break the match.
*/

(async () => {
  const APPLY = false;                    // <-- set true to actually write
  const base  = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const OI_ID = "d6468ec5-c7b5-44a3-8ce0-f81f059b671d";   // Order Items
  const GENERIC_WEEKS = 26;

  const LEAD = [
    {
      "frm13": "ALABAMA POWER",
      "client": "ALABAMA POWER",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "Gauges",
      "s1": "Richards Manuf.",
      "p2": null,
      "s2": null
    },
    {
      "frm13": "AUSTIN ENERGY",
      "client": "AUSTIN ENERGY",
      "weeks": 16,
      "delai": "16 SEM",
      "p1": "Flexible Connector",
      "s1": "Groupe Exel Inter.",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "EPCOR",
      "client": "EPCOR",
      "weeks": 18,
      "delai": "18 SEM",
      "p1": "Radiateurs en SS",
      "s1": "Trantech",
      "p2": "Flexible Connector",
      "s2": "Groupe Exel Inter."
    },
    {
      "frm13": "GEORGIA POWER",
      "client": "GEORGIA POWER",
      "weeks": 18,
      "delai": "18 SEM",
      "p1": "Radiateurs en SS",
      "s1": "Trantech",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "KORTICK",
      "client": "KORTICK",
      "weeks": 16,
      "delai": "16 sem",
      "p1": "Flexible Connector",
      "s1": "Groupe Exel Inter.",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "LG&E",
      "client": "LG&E",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "Gauges",
      "s1": "Richards Manuf.",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "NASHVILLE ELECTRIC",
      "client": "NASHVILLE ELECTRIC",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "Gauges",
      "s1": "Richards Manuf.",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "CITY OF RED DEER",
      "client": "RED DEER",
      "weeks": 18,
      "delai": "18 SEM",
      "p1": "Radiateurs en SS",
      "s1": "Trantech",
      "p2": null,
      "s2": null
    },
    {
      "frm13": "TORONTO HYDRO",
      "client": "TORONTO HYDRO",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "Gauges",
      "s1": "Richards Manuf.",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "HYDRO OTTAWA",
      "client": "OTTAWA HYDRO",
      "weeks": 18,
      "delai": "18 SEM",
      "p1": "Radiateurs",
      "s1": "Trantech",
      "p2": null,
      "s2": null
    },
    {
      "frm13": "PSE§G ",
      "client": "PSE§G ",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "LV Bushing (welded)",
      "s1": "HJ International",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "XCEL ENERGY NORTHERN",
      "client": "XCEL ENERGY NORTHERN",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "LV Bushing (welded)",
      "s1": "HJ International",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "ENMAX",
      "client": "ENMAX",
      "weeks": 20,
      "delai": "20 SEM",
      "p1": "Network Protector",
      "s1": "Richards Manuf.",
      "p2": "Radiateurs en SS",
      "s2": "Trantech"
    },
    {
      "frm13": "HYDRO QUEBEC",
      "client": "HYDRO QUEBEC",
      "weeks": 28,
      "delai": "28 SEM",
      "p1": "Various",
      "s1": null,
      "p2": null,
      "s2": null
    },
    {
      "frm13": "MADISON GAS § ELECTRIC",
      "client": "MADISON GAS § ELECTRIC",
      "weeks": 16,
      "delai": "16 SEM",
      "p1": "Flexible Connector",
      "s1": "Groupe Exel Inter.",
      "p2": "Network Switch",
      "s2": "Quality Switch"
    },
    {
      "frm13": "CONED",
      "client": "CONED",
      "weeks": 24,
      "delai": "24 SEM",
      "p1": "Gauges",
      "s1": "United Inst.",
      "p2": "Bushings",
      "s2": "ABB"
    },
    {
      "frm13": "First Energy",
      "client": "First Energy",
      "weeks": 18,
      "delai": "18 SEM",
      "p1": "Radiateurs ",
      "s1": "Trantech",
      "p2": "Porte Fusible SM-5S",
      "s2": "PTS Elect."
    }
  ];

  const J = async (u, o) => {
    const r = await fetch(u, Object.assign({credentials:"include",
      headers:{Accept:"application/json;odata=nometadata"}}, o||{}));
    if (!r.ok) return {__err: r.status + " " + (await r.text()).slice(0,200)};
    return r.status === 204 ? {} : r.json();
  };
  const xe = s => String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;")
                           .replace(/>/g,"&gt;").replace(/"/g,"&quot;");

  // ------------------------------------------------------------- resolve lists
  const cl = await J(base+"/_api/web/lists/getbytitle('Clients')?$select=Id,ListItemEntityTypeFullName");
  if (cl.__err) { console.error("cannot read the Clients list: "+cl.__err); return; }
  console.log("Clients list id: " + cl.Id + "   <-- gen_n3_flows.py needs this for the sync flow");

  const cols = async id => {
    const j = await J(base+"/_api/v2.0/sites/root/lists/"+id+"/columns");
    return j.__err ? null : (j.value||[]);
  };
  const have   = new Set(((await cols(cl.Id))||[]).map(c=>c.name));
  const haveOI = new Set(((await cols(OI_ID))||[]).map(c=>c.name));
  if (!have.size || !haveOI.size) { console.error("ABORT: read 0 columns from a list."); return; }

  // ------------------------------------------------------------ what to create
  const NEW_CLIENT_COLS = [
    ["CliLeadTimeWeeks", "Number", "Lead Time (weeks)", 'Decimals="0"'],
    ["CliDelai",         "Text",   "Delai",            ""],
    ["CliCriticalPart1", "Text",   "Critical Part 1",  ""],
    ["CliSupplier1",     "Text",   "Supplier 1",       ""],
    ["CliCriticalPart2", "Text",   "Critical Part 2",  ""],
    ["CliSupplier2",     "Text",   "Supplier 2",       ""],
  ];
  // Only one column goes onto Order Items: the number the two date formulas
  // consume. The critical-part and supplier fields are reference data for the
  // Clients list; copied onto 1,124 units they would be dead weight.
  const NEW_OI_COLS = [
    ["CliLeadTimeWeeks", "Number", "Client - Lead Time (weeks)", 'Decimals="0"'],
  ];

  const plan = {clients:    NEW_CLIENT_COLS.filter(c=>!have.has(c[0])),
                orderItems: NEW_OI_COLS.filter(c=>!haveOI.has(c[0]))};
  console.log("\n=== columns to create ===");
  console.log("  Clients    : " + (plan.clients.map(c=>c[0]).join(", ") || "none, all present"));
  console.log("  Order Items: " + (plan.orderItems.map(c=>c[0]).join(", ") || "none, all present"));

  // ---------------------------------------------------------------- match rows
  const items = await J(base+"/_api/web/lists(guid'"+cl.Id+"')/items?$select=Id,Title,Client_ID&$top=500");
  if (items.__err || !(items.value||[]).length) { console.error("ABORT: read 0 client rows."); return; }
  const norm = s => (s||"").normalize("NFKD").replace(/[^A-Za-z0-9]/g,"").toUpperCase();
  const byName = new Map(items.value.map(c=>[norm(c.Title), c]));
  console.log("\nclient rows read: " + items.value.length);

  const seed = [], unmatched = [];
  for (const l of LEAD) {
    const c = byName.get(norm(l.client));
    if (c) seed.push(Object.assign({id:c.Id, title:c.Title}, l)); else unmatched.push(l);
  }
  console.log("\n=== seeding plan : " + seed.length + " of " + LEAD.length + " clients ===");
  for (const s of seed) console.log("  " + String(s.title).padEnd(26) + s.weeks + " weeks"
      + (s.frm13 !== s.client ? "   (FRM13 calls it " + s.frm13 + ")" : ""));
  if (unmatched.length) {
    console.log("\n  NOT MATCHED -- these carry a lead time nothing will pick up:");
    for (const u of unmatched) console.log("     " + u.client + "  (" + u.weeks + " weeks)");
  }
  console.log("\n  every other client falls back to the generic " + GENERIC_WEEKS + " weeks,");
  console.log("  FRM13's own GENERIC VALUE -- not the 52 the Excel formula defaults to.");

  if (!APPLY) { console.log("\nDRY RUN -- nothing written. Set APPLY = true and paste again."); return; }

  const dg = await (await fetch(base+"/_api/contextinfo",{method:"POST",credentials:"include",
    headers:{Accept:"application/json;odata=nometadata"}})).json();
  const H = {Accept:"application/json;odata=nometadata",
             "Content-Type":"application/json;odata=verbose",
             "X-RequestDigest":dg.FormDigestValue};

  console.log("\n=== UNDO ===");
  console.log("columns created (delete these to roll back): " +
    JSON.stringify({Clients: plan.clients.map(c=>c[0]), OrderItems: plan.orderItems.map(c=>c[0])}));
  console.log("client rows seeded (all had these columns empty before): " +
    JSON.stringify(seed.map(s=>s.id)));

  // ------------------------------------------------------------ create columns
  const mk = async (listTitle, c) => {
    const xml = '<Field Type="'+c[1]+'" Name="'+c[0]+'" StaticName="'+c[0]+'" DisplayName="'
              + xe(c[2]) + '" Group="Client Sync" Required="FALSE" ' + c[3] + ' />';
    const r = await fetch(base+"/_api/web/lists/getbytitle('"+listTitle+"')/fields/createfieldasxml",
      {method:"POST", credentials:"include", headers:H,
       body: JSON.stringify({parameters:{__metadata:{type:"SP.XmlSchemaFieldCreationInformation"},
                                         SchemaXml: xml,
                                         // 🔴 Options: 8 = AddFieldInternalNameHint.
                                         // WITHOUT IT createfieldasxml IGNORES `Name`
                                         // and derives the internal name from
                                         // DisplayName -- percent-encoded and cut at
                                         // 32 chars. Omitting it produced
                                         // `Lead_x0020_Time_x0020__x0028_wee` instead
                                         // of `CliLeadTimeWeeks`, four times over,
                                         // because the existence check then never
                                         // matched. n2_create_columns.js documents
                                         // this in its own header; see n5b for the
                                         // cleanup. Deliberately NOT 8|16 -- 16 is
                                         // AddFieldToDefaultView.
                                         Options: 8}})});
    console.log((r.ok ? "created " : "FAILED "+r.status+" ") + listTitle + "." + c[0]
                + (r.ok ? "" : " " + (await r.text()).slice(0,200)));
  };
  for (const c of plan.clients)    await mk("Clients", c);
  for (const c of plan.orderItems) await mk("Order Items", c);

  // 🔴 CONFIRM THE COLUMNS EXIST UNDER THE NAMES WE ASKED FOR, then wait for the
  // schema. Two different failures hide behind the same symptom:
  //   - the internal name is not what we asked for (no Options: 8) -- permanent,
  //     and re-running makes it worse by creating another set
  //   - the schema has not refreshed yet -- transient, fixed by waiting
  // Polling on the NAMES WE WANT distinguishes them: a name that never appears is
  // the first case, and the loop below says so instead of timing out silently.
  // createfieldasxml returns 200 and the column really is created, but the list's
  // OData entity type is cached, so an immediate write to it fails with
  //     The property 'CliLeadTimeWeeks' does not exist
  // and a $select naming it returns 400. Seen on the first real run, 2026-09-10:
  // 7 columns created, all 17 seeds rejected, nothing written.
  //
  // Harmless in that nothing partial lands -- but without this the script reports a
  // total failure that reads like a bad field name, when the fix is to wait a moment.
  if (plan.clients.length || plan.orderItems.length) {
    const want = plan.clients.map(c => c[0]);
    process_wait: for (let a = 1; a <= 12; a++) {
      await new Promise(r => setTimeout(r, 2500));
      const now = new Set(((await cols(cl.Id)) || []).map(c => c.name));
      const missing = want.filter(n => !now.has(n));
      if (!missing.length) {
        console.log("schema caught up after " + (a * 2.5) + "s");
        break process_wait;
      }
      console.log("  waiting for the list schema (" + missing.length + " column(s) not visible yet)…");
      if (a === 12) {
        console.error("after 30s these names are still not on the list: " + missing.join(", "));
        console.error("");
        console.error("That is almost certainly NOT a caching delay -- it means the columns");
        console.error("were created under different internal names, which happens when");
        console.error("createfieldasxml is called without Options: 8. Check the list in the");
        console.error("UI: if columns with these DISPLAY names exist but the internal names");
        console.error("differ, run n5b_cleanup_bad_columns.js first, then re-run this.");
        console.error("");
        console.error("Nothing was seeded.");
        return;
      }
    }
  }

  // --------------------------------------------------------------- seed values
  let ok=0, fail=0;
  for (const s of seed) {
    const body = {__metadata:{type: cl.ListItemEntityTypeFullName},
                  CliLeadTimeWeeks: s.weeks, CliDelai: s.delai || null,
                  CliCriticalPart1: s.p1 || null, CliSupplier1: s.s1 || null,
                  CliCriticalPart2: s.p2 || null, CliSupplier2: s.s2 || null};
    const r = await fetch(base+"/_api/web/lists(guid'"+cl.Id+"')/items("+s.id+")",
      {method:"POST", credentials:"include",
       headers: Object.assign({"X-HTTP-Method":"MERGE","IF-MATCH":"*"}, H),
       body: JSON.stringify(body)});
    if (r.ok) ok++;
    else {
      fail++;
      const t = await r.text();
      console.error("  " + s.title + " -> " + r.status + " " + t.slice(0,160));
      if (t.indexOf("does not exist") >= 0) {
        console.error("  ^ the list schema has not picked up the new column yet.");
        console.error("    Nothing has been written. Wait a moment and re-run this script.");
        return;
      }
    }
  }
  console.log("\nseeded ok=" + ok + " failed=" + fail);

  // ------------------------------------------------------------- verification
  const after = await J(base+"/_api/web/lists(guid'"+cl.Id+"')/items?$select=Id,Title,CliLeadTimeWeeks&$top=500");
  const got = new Map((after.value||[]).map(c=>[c.Id, c.CliLeadTimeWeeks]));
  let bad=0;
  for (const s of seed) if (Number(got.get(s.id)) !== Number(s.weeks)) {
    bad++; console.error("  wrong: " + s.title + " = " + got.get(s.id) + ", expected " + s.weeks);
  }
  const filled = (after.value||[]).filter(c=>c.CliLeadTimeWeeks != null).length;
  console.log("\n--- verification (trust this, not the write results) ---");
  console.log("clients with a lead time : " + filled + "   (expect " + seed.length + ")");
  console.log("values wrong             : " + bad + "   (expect 0)");
  console.log("\nNEXT");
  console.log("  1. put the Clients list id printed above into LISTS['Clients'] in gen_n3_flows.py");
  console.log("  2. python scripts/gen_n3_flows.py && python scripts/verify_n3_flows.py");
  console.log("  3. build a 'Clients - Create or Update Trigger' shell, then");
  console.log("     python scripts/apply_n3_definition.py --flow '<folder>' --defn Order_Items__sync_from_Clients");
  console.log("  4. only then the Ing. Due Date calculated column -- it needs the number present first");
})();
