/* N6 -- backfill Order.Lead Time from the client's lead time.

   GENERATED by scripts/gen_n6_order_lead_time.py. Edit the template, not the output.

   HOW TO RUN
     1. Open, signed in:
        https://ermcopower.sharepoint.com/sites/PioneerPlanificatio/_api/web/currentuser
     2. F12 -> Console. Paste this whole file. Press Enter.
     3. DRY RUN by default. Read the plan, then set APPLY = true and paste again.
     4. It prints an UNDO block with every previous value, and verifies by read-back.

   WHY EVERY ROW, NOT JUST THE DEFAULTS
     Measured on the 2026-09-09 export, of the orders whose client has a lead time:

       275  Order.Lead Time is exactly 26  -- the untouched column default
        91  a different value              -- e.g. 84 HYDRO QUEBEC orders at 20
        38  already agrees

     My first read of the 91 was that they might be deliberate per-order overrides,
     and that overwriting them would destroy something. The user corrected that:
     they are a ONE-TIME FILL AT ORDER CREATION that has never been re-synced. So
     they are stale copies of whatever the client's lead time was that day -- not
     judgement, just age. There is nothing to preserve, and leaving them is worse
     than fixing them: an order quoting 20 weeks for a client whose real lead time
     is 28 is wrong in the direction that hurts.

     The UNDO block below carries every previous value regardless, because "the user
     told me they are stale" is a good reason to proceed and a bad reason to have no
     way back.

   WHAT IT DOES NOT TOUCH
     Orders whose client has no lead time in FRM13. They keep whatever they have and
     fall back to the generic 26 weeks in the formulas, which is FRM13's own
     GENERIC VALUE. Note the Excel formula defaults to 52 instead -- that
     contradiction is real, predates this, and is not settled here.
*/

(async () => {
  const APPLY = false;                    // <-- set true to actually write
  const base  = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const ORDER = "6fe35dfe-2b7d-455a-abe3-056abb386733";
  const CLIENTS = "3bcf7d97-0862-404d-ab3f-eeaa358c05d8";
  const GENERIC_WEEKS = 26;

  const J = async u => {
    const r = await fetch(u, {credentials:"include",
      headers:{Accept:"application/json;odata=nometadata"}});
    if (!r.ok) return {__err: r.status + " " + (await r.text()).slice(0,200)};
    return r.json();
  };
  const page = async u => { let o=[],g=0;
    while (u && g++<30){ const j=await J(u); if (j.__err){console.error(j.__err); return null;}
      o=o.concat(j.value||[]); u=j["odata.nextLink"]||null; } return o; };
  const norm = s => (s||"").normalize("NFKD").replace(/[^A-Za-z0-9]/g,"").toUpperCase();

  // ------------------------------------------------------- the client lead times
  const clients = await page(base+"/_api/web/lists(guid'"+CLIENTS+"')/items"
                             +"?$select=Id,Title,CliLeadTimeWeeks&$top=500");
  if (!clients || !clients.length) { console.error("ABORT: read 0 clients."); return; }
  const byId = new Map(), byName = new Map();
  for (const c of clients) {
    if (c.CliLeadTimeWeeks == null || c.CliLeadTimeWeeks === "") continue;
    byId.set(c.Id, {weeks: Number(c.CliLeadTimeWeeks), title: c.Title});
    byName.set(norm(c.Title), {weeks: Number(c.CliLeadTimeWeeks), title: c.Title});
  }
  console.log("clients read: " + clients.length + " | with a lead time: " + byId.size);
  if (!byId.size) { console.error("ABORT: no client carries a lead time. Run n5 first."); return; }

  // ------------------------------------------------- find Order's Client lookup
  // DISCOVERED, never guessed. A lookup's internal name does not appear in a CSV
  // export at all -- values or schema -- and this repo has already been bitten by
  // assuming one. Ask the v2.0 columns endpoint which lookup points at the Clients
  // list, and use whatever it says.
  const ocols = await J(base+"/_api/v2.0/sites/root/lists/"+ORDER+"/columns");
  if (ocols.__err) { console.error("cannot read Order columns: "+ocols.__err); return; }
  const lk = (ocols.value||[]).filter(c => c.lookup && c.lookup.listId
                    && String(c.lookup.listId).toLowerCase().indexOf(CLIENTS.slice(0,8)) >= 0);
  if (!lk.length) {
    console.error("no lookup on Order points at the Clients list. Lookups found:");
    for (const c of (ocols.value||[])) if (c.lookup)
      console.error("   " + c.name.padEnd(28) + " -> " + (c.lookup.listId||"?"));
    console.error("Without it this can still match on the stale text mirror, but that");
    console.error("has been unsynced since 2026-08-21 -- fix the lookup instead.");
    return;
  }
  const CLIENT_FIELD = lk[0].name + "Id";
  console.log("Order's Client lookup: " + lk[0].name + "  (filtering on " + CLIENT_FIELD + ")");

  // ------------------------------------------------------------------ the orders
  // Take the lookup id AND the text mirror: the lookup is the real join, the mirror
  // is only a fallback for rows where the lookup was never set. The mirror has been
  // stale since 2026-08-21, so it is used for MATCHING only, never for a value.
  let orders = await page(base+"/_api/web/lists(guid'"+ORDER+"')/items"
      +"?$select=Id,Order_x0020_Number1,Lead_x0020_Time,Client_ID_TextField,"
      + CLIENT_FIELD + "&$top=500");
  if (!orders) { console.error("reading orders failed -- see the error above."); return; }
  if (!orders.length) { console.error("ABORT: read 0 orders."); return; }
  console.log("orders read : " + orders.length);

  const plan = [], noClient = [], noLead = [], same = [];
  for (const o of orders) {
    const hit = byId.get(o[CLIENT_FIELD]) || byName.get(norm(o.Client_ID_TextField));
    if (!hit) {
      if (o[CLIENT_FIELD] == null && !o.Client_ID_TextField) noClient.push(o);
      else noLead.push(o);
      continue;
    }
    const cur = (o.Lead_x0020_Time == null || o.Lead_x0020_Time === "") ? null : Number(o.Lead_x0020_Time);
    if (cur === hit.weeks) { same.push(o); continue; }
    plan.push({Id:o.Id, num:o.Order_x0020_Number1, client:hit.title, from:cur, to:hit.weeks});
  }

  console.log("\n=== plan ===");
  console.log("  to update                    : " + plan.length);
  console.log("  already correct              : " + same.length);
  console.log("  client has no lead time      : " + noLead.length
              + "   (left alone -- they fall back to the generic " + GENERIC_WEEKS + ")");
  console.log("  order has no client at all   : " + noClient.length);

  const byFrom = {};
  for (const p of plan) { const k = (p.from == null ? "(empty)" : p.from); byFrom[k] = (byFrom[k]||0)+1; }
  console.log("\n  what is being replaced:");
  for (const k of Object.keys(byFrom).sort()) console.log("     " + String(k).padStart(8) + "  ->  " + byFrom[k] + " order(s)");
  console.log("\n  sample:");
  for (const p of plan.slice(0,8))
    console.log("     " + String(p.num).padEnd(12) + String(p.client).padEnd(24)
                + String(p.from == null ? "(empty)" : p.from).padStart(7) + "  ->  " + p.to);

  if (!plan.length) { console.log("\nnothing to do."); return; }
  if (!APPLY) { console.log("\nDRY RUN -- nothing written. Set APPLY = true and paste again."); return; }

  console.log("\n=== UNDO -- every previous value, paste into the block at the bottom ===");
  console.log(JSON.stringify(plan.map(p => ({Id:p.Id, num:p.num, was:p.from}))));

  const dg = await (await fetch(base+"/_api/contextinfo",{method:"POST",credentials:"include",
    headers:{Accept:"application/json;odata=nometadata"}})).json();
  const et = (await J(base+"/_api/web/lists(guid'"+ORDER+"')?$select=ListItemEntityTypeFullName"))
             .ListItemEntityTypeFullName;

  let ok=0, fail=0; const errs=[];
  const CONC = 4;
  const patch = async p => {
    for (let a=1; a<=4; a++) {
      const r = await fetch(base+"/_api/web/lists(guid'"+ORDER+"')/items("+p.Id+")",{
        method:"POST", credentials:"include",
        headers:{Accept:"application/json;odata=nometadata",
                 "Content-Type":"application/json;odata=verbose",
                 "X-RequestDigest":dg.FormDigestValue,
                 "X-HTTP-Method":"MERGE","IF-MATCH":"*"},
        body: JSON.stringify({__metadata:{type:et}, Lead_x0020_Time: p.to})});
      if (r.ok) { ok++; return; }
      if (!(r.status===409 || r.status===429 || r.status>=500) || a===4) {
        fail++; if (errs.length<8) errs.push(p.num+": "+r.status+" "+(await r.text()).slice(0,160));
        return;
      }
      await new Promise(z=>setTimeout(z, 250*Math.pow(2,a-1)+Math.random()*200));
    }
  };
  console.log("\nwriting " + plan.length + " ...");
  for (let i=0;i<plan.length;i+=CONC) {
    await Promise.all(plan.slice(i,i+CONC).map(patch));
    if (i % 100 === 0) console.log("  " + Math.min(i+CONC, plan.length) + "/" + plan.length);
  }
  console.log("written ok=" + ok + " failed=" + fail);
  for (const e of errs) console.error("  " + e);

  // ------------------------------------------------------------- verification
  const after = await page(base+"/_api/web/lists(guid'"+ORDER+"')/items"
      +"?$select=Id,Order_x0020_Number1,Lead_x0020_Time&$top=500");
  const want = new Map(plan.map(p=>[p.Id,p.to]));
  let bad=0;
  for (const o of (after||[])) {
    if (!want.has(o.Id)) continue;
    if (Number(o.Lead_x0020_Time) !== want.get(o.Id)) {
      bad++; if (bad<=6) console.error("  wrong: " + o.Order_x0020_Number1
                  + " = " + o.Lead_x0020_Time + ", expected " + want.get(o.Id));
    }
  }
  console.log("\n--- verification (trust this, not the write results) ---");
  console.log("orders checked : " + want.size);
  console.log("values wrong   : " + bad + "   (expect 0)");
})();

/* ---------------------------------------------------------------- UNDO ----
   Puts every Lead Time back to what it was.

(async () => {
  const base="https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const ORDER="6fe35dfe-2b7d-455a-abe3-056abb386733";
  const MADE=[];   // <- paste the UNDO array here
  const dg=await (await fetch(base+"/_api/contextinfo",{method:"POST",credentials:"include",
    headers:{Accept:"application/json;odata=nometadata"}})).json();
  const et=(await (await fetch(base+"/_api/web/lists(guid'"+ORDER+"')?$select=ListItemEntityTypeFullName",
    {credentials:"include",headers:{Accept:"application/json;odata=nometadata"}})).json()).ListItemEntityTypeFullName;
  let ok=0;
  for (const m of MADE) {
    const r=await fetch(base+"/_api/web/lists(guid'"+ORDER+"')/items("+m.Id+")",{method:"POST",
      credentials:"include",
      headers:{Accept:"application/json;odata=nometadata","Content-Type":"application/json;odata=verbose",
               "X-RequestDigest":dg.FormDigestValue,"X-HTTP-Method":"MERGE","IF-MATCH":"*"},
      body:JSON.stringify({__metadata:{type:et}, Lead_x0020_Time: m.was})});
    if (r.ok) ok++; else console.error(m.num+" -> "+r.status);
  }
  console.log("restored "+ok+" of "+MADE.length);
})();
---------------------------------------------------------------------------- */
