/* N9 -- create the five calculated columns ported from FRM10-12.
   GENERATED by scripts/gen_calc_columns.py -- regenerate, do not hand-edit.

   Paste into the browser console on the SharePoint site.

   DRY RUN by default: it creates nothing until APPLY = true.

   It creates EIGHT columns, Estimated Delivery Date included, in dependency order.
   Nothing has to exist first -- but the whole chain is calculated, so each row is only
   as fresh as its last write. TODAY() freezes at last save, which is exactly what the
   nightly touch stage in the cleanup flow exists to fix for the stalled rows.
   See docs/calc-columns-port.md.
*/
(async () => {
  const APPLY = false;
  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const LIST = "Order Items";
  const EDD_INTERNAL = "EstimatedDeliveryDate";

  const J = async u => (await fetch(u, {credentials:"include",
              headers:{Accept:"application/json;odata=nometadata"}})).json();

  const FIELDS = [
    {
        "name": "CalcRefreshed",
        "rtype": "DateTime",
        "refs": [],
        "formula": "",
        "xml": "<Field Type=\"DateTime\" DisplayName=\"Calc Refreshed\" Name=\"CalcRefreshed\" StaticName=\"CalcRefreshed\" Required=\"FALSE\" Group=\"Calculated\" Format=\"DateOnly\" />"
    },
    {
        "name": "BoPenalty",
        "rtype": "Number",
        "refs": [
            "BO"
        ],
        "formula": "=IF(OR(LOWER(TRIM([BO]))=\"ok\",TRIM([BO])=\"\"),0,30)",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Bo Penalty\" Name=\"BoPenalty\" StaticName=\"BoPenalty\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Number\" Decimals=\"0\"><Formula>=IF(OR(LOWER(TRIM([BO]))=&quot;ok&quot;,TRIM([BO])=&quot;&quot;),0,30)</Formula><FieldRefs><FieldRef Name=\"BO\" /></FieldRefs></Field>"
    },
    {
        "name": "EstimatedDeliveryDate",
        "rtype": "DateTime",
        "refs": [
            "Planned_x0020_Delivery_x0020_Dat",
            "ManualEstimatedDeliveryDate",
            "FinishingDate",
            "TestingDate",
            "Planned_x0020_Tanking_x0020_Date",
            "TankDeliveryDate",
            "OrdOrderDate",
            "CliLeadTimeWeeks",
            "BoPenalty",
            "CoilingDate",
            "StackingDate",
            "AssemblyDate",
            "DryingDate"
        ],
        "formula": "=IF(NOT(ISBLANK([Planned Delivery Date])),[Planned Delivery Date],IF(NOT(ISBLANK([Manual Estimated Delivery Date])),[Manual Estimated Delivery Date],IF(NOT(ISBLANK([Finishing End Date])),MAX(TODAY(),[Finishing End Date])+7+[Bo Penalty],IF(NOT(ISBLANK([Testing End Date])),MAX(TODAY(),[Testing End Date])+10+[Bo Penalty],IF(NOT(ISBLANK([Planned Tanking Date])),MAX(TODAY(),[Planned Tanking Date])+14+[Bo Penalty],IF(OR(NOT(ISBLANK([Coiling End Date])),NOT(ISBLANK([Stacking End Date])),NOT(ISBLANK([Assembly End Date])),NOT(ISBLANK([Drying End Date]))),MAX(TODAY(),[Coiling End Date],[Stacking End Date],[Assembly End Date],[Drying End Date],[Tank Delivery Date])+21+[Bo Penalty],IF(NOT(ISBLANK([Order - Order Date])),[Order - Order Date]+90+(IF(ISBLANK([Client - Lead Time (weeks)]),26,[Client - Lead Time (weeks)]))*7,\"\")))))))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Estimated Delivery Date\" Name=\"EstimatedDeliveryDate\" StaticName=\"EstimatedDeliveryDate\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"DateTime\"><Formula>=IF(NOT(ISBLANK([Planned Delivery Date])),[Planned Delivery Date],IF(NOT(ISBLANK([Manual Estimated Delivery Date])),[Manual Estimated Delivery Date],IF(NOT(ISBLANK([Finishing End Date])),MAX(TODAY(),[Finishing End Date])+7+[Bo Penalty],IF(NOT(ISBLANK([Testing End Date])),MAX(TODAY(),[Testing End Date])+10+[Bo Penalty],IF(NOT(ISBLANK([Planned Tanking Date])),MAX(TODAY(),[Planned Tanking Date])+14+[Bo Penalty],IF(OR(NOT(ISBLANK([Coiling End Date])),NOT(ISBLANK([Stacking End Date])),NOT(ISBLANK([Assembly End Date])),NOT(ISBLANK([Drying End Date]))),MAX(TODAY(),[Coiling End Date],[Stacking End Date],[Assembly End Date],[Drying End Date],[Tank Delivery Date])+21+[Bo Penalty],IF(NOT(ISBLANK([Order - Order Date])),[Order - Order Date]+90+(IF(ISBLANK([Client - Lead Time (weeks)]),26,[Client - Lead Time (weeks)]))*7,&quot;&quot;)))))))</Formula><FieldRefs><FieldRef Name=\"Planned_x0020_Delivery_x0020_Dat\" /><FieldRef Name=\"ManualEstimatedDeliveryDate\" /><FieldRef Name=\"FinishingDate\" /><FieldRef Name=\"TestingDate\" /><FieldRef Name=\"Planned_x0020_Tanking_x0020_Date\" /><FieldRef Name=\"TankDeliveryDate\" /><FieldRef Name=\"OrdOrderDate\" /><FieldRef Name=\"CliLeadTimeWeeks\" /><FieldRef Name=\"BoPenalty\" /><FieldRef Name=\"CoilingDate\" /><FieldRef Name=\"StackingDate\" /><FieldRef Name=\"AssemblyDate\" /><FieldRef Name=\"DryingDate\" /></FieldRefs></Field>"
    },
    {
        "name": "IsCanadian",
        "rtype": "Boolean",
        "refs": [
            "OrdProvinceState"
        ],
        "formula": "=OR(LOWER(TRIM([Order - Province/State]))=\"ab\",LOWER(TRIM([Order - Province/State]))=\"bc\",LOWER(TRIM([Order - Province/State]))=\"mb\",LOWER(TRIM([Order - Province/State]))=\"nb\",LOWER(TRIM([Order - Province/State]))=\"nl\",LOWER(TRIM([Order - Province/State]))=\"nt\",LOWER(TRIM([Order - Province/State]))=\"ns\",LOWER(TRIM([Order - Province/State]))=\"nu\",LOWER(TRIM([Order - Province/State]))=\"on\",LOWER(TRIM([Order - Province/State]))=\"pe\",LOWER(TRIM([Order - Province/State]))=\"qc\",LOWER(TRIM([Order - Province/State]))=\"sk\",LOWER(TRIM([Order - Province/State]))=\"yt\")",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Is Canadian\" Name=\"IsCanadian\" StaticName=\"IsCanadian\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Boolean\"><Formula>=OR(LOWER(TRIM([Order - Province/State]))=&quot;ab&quot;,LOWER(TRIM([Order - Province/State]))=&quot;bc&quot;,LOWER(TRIM([Order - Province/State]))=&quot;mb&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nb&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nl&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nt&quot;,LOWER(TRIM([Order - Province/State]))=&quot;ns&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nu&quot;,LOWER(TRIM([Order - Province/State]))=&quot;on&quot;,LOWER(TRIM([Order - Province/State]))=&quot;pe&quot;,LOWER(TRIM([Order - Province/State]))=&quot;qc&quot;,LOWER(TRIM([Order - Province/State]))=&quot;sk&quot;,LOWER(TRIM([Order - Province/State]))=&quot;yt&quot;)</Formula><FieldRefs><FieldRef Name=\"OrdProvinceState\" /></FieldRefs></Field>"
    },
    {
        "name": "FxYear",
        "rtype": "Number",
        "refs": [
            "EstimatedDeliveryDate",
            "OrdInitialPromisedDate"
        ],
        "formula": "=IF(AND(ISBLANK([Estimated Delivery Date]),ISBLANK([Order - Initial Promised Date])),0,YEAR(IF(ISBLANK([Estimated Delivery Date]),[Order - Initial Promised Date],[Estimated Delivery Date])))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Fx Year\" Name=\"FxYear\" StaticName=\"FxYear\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Number\" Decimals=\"0\"><Formula>=IF(AND(ISBLANK([Estimated Delivery Date]),ISBLANK([Order - Initial Promised Date])),0,YEAR(IF(ISBLANK([Estimated Delivery Date]),[Order - Initial Promised Date],[Estimated Delivery Date])))</Formula><FieldRefs><FieldRef Name=\"EstimatedDeliveryDate\" /><FieldRef Name=\"OrdInitialPromisedDate\" /></FieldRefs></Field>"
    },
    {
        "name": "FxRate",
        "rtype": "Number",
        "refs": [
            "FxYear"
        ],
        "formula": "=IF([Fx Year]=0,0,IF([Fx Year]<=2024,1.35,IF([Fx Year]=2025,1.44,IF([Fx Year]=2026,1.38,IF([Fx Year]=2027,1.39,IF([Fx Year]=2028,1.43,1.47))))))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Fx Rate\" Name=\"FxRate\" StaticName=\"FxRate\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Number\" Decimals=\"4\"><Formula>=IF([Fx Year]=0,0,IF([Fx Year]&lt;=2024,1.35,IF([Fx Year]=2025,1.44,IF([Fx Year]=2026,1.38,IF([Fx Year]=2027,1.39,IF([Fx Year]=2028,1.43,1.47))))))</Formula><FieldRefs><FieldRef Name=\"FxYear\" /></FieldRefs></Field>"
    },
    {
        "name": "PriceCAD",
        "rtype": "Currency",
        "refs": [
            "IsCanadian",
            "OrdPrice",
            "FxRate"
        ],
        "formula": "=IF([Is Canadian],[Order - Price],IF([Fx Rate]=0,\"\",[Order - Price]*[Fx Rate]))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Price CAD\" Name=\"PriceCAD\" StaticName=\"PriceCAD\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Currency\" Decimals=\"2\" LCID=\"1033\"><Formula>=IF([Is Canadian],[Order - Price],IF([Fx Rate]=0,&quot;&quot;,[Order - Price]*[Fx Rate]))</Formula><FieldRefs><FieldRef Name=\"IsCanadian\" /><FieldRef Name=\"OrdPrice\" /><FieldRef Name=\"FxRate\" /></FieldRefs></Field>"
    },
    {
        "name": "PriceUSD",
        "rtype": "Currency",
        "refs": [
            "IsCanadian",
            "OrdPrice",
            "FxRate"
        ],
        "formula": "=IF([Is Canadian],IF([Fx Rate]=0,\"\",[Order - Price]/[Fx Rate]),[Order - Price])",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Price USD\" Name=\"PriceUSD\" StaticName=\"PriceUSD\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Currency\" Decimals=\"2\" LCID=\"1033\"><Formula>=IF([Is Canadian],IF([Fx Rate]=0,&quot;&quot;,[Order - Price]/[Fx Rate]),[Order - Price])</Formula><FieldRefs><FieldRef Name=\"IsCanadian\" /><FieldRef Name=\"OrdPrice\" /><FieldRef Name=\"FxRate\" /></FieldRefs></Field>"
    }
];

  // ---------------------------------------------------------------- preflight
  const f = await J(base + "/_api/web/lists/getbytitle('" + LIST + "')/fields"
              + "?$select=InternalName,TypeAsString&$top=500");
  if (!f.value || !f.value.length) { console.error("ABORT: read 0 fields."); return; }
  const have = new Map(f.value.map(x => [x.InternalName, x.TypeAsString]));

  const edd = have.get(EDD_INTERNAL);
  if (edd) {
    console.error("ABORT: '" + EDD_INTERNAL + "' already exists (type " + edd + ").");
    console.error("  This script CREATES it. If a stored version was built first, decide");
    console.error("  which one wins before running -- do not end up with both, and note");
    console.error("  that a stored one can be hand-edited, which is the whole reason this");
    console.error("  chain is calculated. See docs/calc-columns-port.md.");
    return;
  }

  const dup = FIELDS.filter(x => have.has(x.name));
  if (dup.length) {
    console.error("ABORT: already present: " + dup.map(d => d.name).join(", "));
    console.error("  Delete them first, or this creates duplicates with a 0 suffix --");
    console.error("  the x9 cleanup exists because that already happened once.");
    return;
  }
  for (const x of FIELDS)
    for (const r of x.refs)
      if (!have.has(r) && !FIELDS.some(y => y.name === r))
        { console.error("ABORT: " + x.name + " references missing field " + r); return; }

  console.table(FIELDS.map(x => ({ field: x.name, type: x.rtype, formula: x.formula })));
  if (!APPLY) { console.log("\nDRY RUN -- nothing created. Set APPLY = true."); return; }

  const dg = await (await fetch(base + "/_api/contextinfo", { method:"POST",
    credentials:"include", headers:{Accept:"application/json;odata=nometadata"} })).json();

  const results = [];
  // Sequential on purpose: Fx Rate references Fx Year and the price columns reference
  // both, and SharePoint rejects a FieldRef to a field that does not exist yet.
  for (const x of FIELDS) {
    try {
      const r = await fetch(base + "/_api/web/lists/getbytitle('" + LIST
        + "')/fields/createfieldasxml", {
        method:"POST", credentials:"include",
        headers:{ Accept:"application/json;odata=nometadata",
                  "Content-Type":"application/json;odata=verbose",
                  "X-RequestDigest": dg.FormDigestValue },
        body: JSON.stringify({ parameters: {
          __metadata:{ type:"SP.XmlSchemaFieldCreationInformation" },
          SchemaXml: x.xml, Options: 8 } })
      });
      results.push({ field:x.name, ok:r.ok, status:r.status,
                     error: r.ok ? "" : (await r.text()).slice(0,300) });
      if (!r.ok) break;   // a later field references this one; stop rather than cascade
    } catch (e) { results.push({ field:x.name, ok:false, status:0, error:String(e) }); break; }
  }
  console.table(results);

  // Read back. A 200 is not proof SharePoint stored the ResultType you asked for --
  // it silently accepts and downgrades some combinations.
  const after = await J(base + "/_api/web/lists/getbytitle('" + LIST + "')/fields"
                  + "?$select=InternalName,TypeAsString,OutputType&$top=500");
  const made = (after.value||[]).filter(x => FIELDS.some(y => y.name === x.InternalName));
  console.log("\n--- read back (trust this, not the POST results) ---");
  console.table(made.map(x => ({ field:x.InternalName, type:x.TypeAsString, output:x.OutputType })));
})();
