/* N9 -- create the five calculated columns ported from FRM10-12.
   GENERATED by scripts/gen_calc_columns.py -- regenerate, do not hand-edit.

   Paste into the browser console on the SharePoint site.

   DRY RUN by default: it creates nothing until APPLY = true.

   IT REFUSES TO RUN until `Estimated Delivery Date` exists as a STORED column on the
   list. Fx Year reads it, and Price CAD / Price USD read Fx Year, so creating the chain
   first would give three columns that silently evaluate against a field that is not
   there. A calculated column cannot read a column-formatting result -- that renders in
   the browser and is never stored. See docs/estimated-delivery-date-today.md.
*/
(async () => {
  const APPLY = false;
  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const LIST = "Order Items";
  const EDD_INTERNAL = "EstimatedDeliveryDate";

  const J = async u => (await fetch(u, {credentials:"include",
              headers:{Accept:"application/json;odata=nometadata"}})).json();

  const FIELDS = [
    {
        "name": "IsCanadian",
        "rtype": "Boolean",
        "refs": [
            "OrdProvinceState"
        ],
        "formula": "=OR(LOWER(TRIM([Order - Province/State]))=\"ab\",LOWER(TRIM([Order - Province/State]))=\"bc\",LOWER(TRIM([Order - Province/State]))=\"mb\",LOWER(TRIM([Order - Province/State]))=\"nb\",LOWER(TRIM([Order - Province/State]))=\"nl\",LOWER(TRIM([Order - Province/State]))=\"nt\",LOWER(TRIM([Order - Province/State]))=\"ns\",LOWER(TRIM([Order - Province/State]))=\"nu\",LOWER(TRIM([Order - Province/State]))=\"on\",LOWER(TRIM([Order - Province/State]))=\"pe\",LOWER(TRIM([Order - Province/State]))=\"qc\",LOWER(TRIM([Order - Province/State]))=\"sk\",LOWER(TRIM([Order - Province/State]))=\"yt\")",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Is Canadian\" Name=\"IsCanadian\" StaticName=\"IsCanadian\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Boolean\"><Formula>=OR(LOWER(TRIM([Order - Province/State]))=&quot;ab&quot;,LOWER(TRIM([Order - Province/State]))=&quot;bc&quot;,LOWER(TRIM([Order - Province/State]))=&quot;mb&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nb&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nl&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nt&quot;,LOWER(TRIM([Order - Province/State]))=&quot;ns&quot;,LOWER(TRIM([Order - Province/State]))=&quot;nu&quot;,LOWER(TRIM([Order - Province/State]))=&quot;on&quot;,LOWER(TRIM([Order - Province/State]))=&quot;pe&quot;,LOWER(TRIM([Order - Province/State]))=&quot;qc&quot;,LOWER(TRIM([Order - Province/State]))=&quot;sk&quot;,LOWER(TRIM([Order - Province/State]))=&quot;yt&quot;)</Formula><FieldRefs><FieldRef Name=\"OrdProvinceState\" /></FieldRefs></Field>"
    },
    {
        "name": "FxYear",
        "rtype": "Number",
        "refs": [
            "EstimatedDeliveryDate",
            "OrdInitialPromisedDate"
        ],
        "formula": "=IF(AND(ISBLANK([Estimated Delivery Date]),ISBLANK([Order - Initial Promised Date])),0,YEAR(IF(ISBLANK([Estimated Delivery Date]),[Order - Initial Promised Date],[Estimated Delivery Date])))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Fx Year\" Name=\"FxYear\" StaticName=\"FxYear\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Number\" Decimals=\"0\"><Formula>=IF(AND(ISBLANK([Estimated Delivery Date]),ISBLANK([Order - Initial Promised Date])),0,YEAR(IF(ISBLANK([Estimated Delivery Date]),[Order - Initial Promised Date],[Estimated Delivery Date])))</Formula><FieldRefs><FieldRef Name=\"EstimatedDeliveryDate\" /><FieldRef Name=\"OrdInitialPromisedDate\" /></FieldRefs></Field>"
    },
    {
        "name": "FxRate",
        "rtype": "Number",
        "refs": [
            "FxYear"
        ],
        "formula": "=IF([Fx Year]=0,0,IF([Fx Year]<=2024,1.35,IF([Fx Year]=2025,1.44,IF([Fx Year]=2026,1.38,IF([Fx Year]=2027,1.39,IF([Fx Year]=2028,1.43,1.47))))))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Fx Rate\" Name=\"FxRate\" StaticName=\"FxRate\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Number\" Decimals=\"4\"><Formula>=IF([Fx Year]=0,0,IF([Fx Year]&lt;=2024,1.35,IF([Fx Year]=2025,1.44,IF([Fx Year]=2026,1.38,IF([Fx Year]=2027,1.39,IF([Fx Year]=2028,1.43,1.47))))))</Formula><FieldRefs><FieldRef Name=\"FxYear\" /></FieldRefs></Field>"
    },
    {
        "name": "PriceCAD",
        "rtype": "Currency",
        "refs": [
            "IsCanadian",
            "OrdPrice",
            "FxRate"
        ],
        "formula": "=IF([Is Canadian],[Order - Price],IF([Fx Rate]=0,\"\",[Order - Price]*[Fx Rate]))",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Price CAD\" Name=\"PriceCAD\" StaticName=\"PriceCAD\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Currency\" Decimals=\"2\" LCID=\"1033\"><Formula>=IF([Is Canadian],[Order - Price],IF([Fx Rate]=0,&quot;&quot;,[Order - Price]*[Fx Rate]))</Formula><FieldRefs><FieldRef Name=\"IsCanadian\" /><FieldRef Name=\"OrdPrice\" /><FieldRef Name=\"FxRate\" /></FieldRefs></Field>"
    },
    {
        "name": "PriceUSD",
        "rtype": "Currency",
        "refs": [
            "IsCanadian",
            "OrdPrice",
            "FxRate"
        ],
        "formula": "=IF([Is Canadian],IF([Fx Rate]=0,\"\",[Order - Price]/[Fx Rate]),[Order - Price])",
        "xml": "<Field Type=\"Calculated\" DisplayName=\"Price USD\" Name=\"PriceUSD\" StaticName=\"PriceUSD\" Required=\"FALSE\" Group=\"Calculated\" ResultType=\"Currency\" Decimals=\"2\" LCID=\"1033\"><Formula>=IF([Is Canadian],IF([Fx Rate]=0,&quot;&quot;,[Order - Price]/[Fx Rate]),[Order - Price])</Formula><FieldRefs><FieldRef Name=\"IsCanadian\" /><FieldRef Name=\"OrdPrice\" /><FieldRef Name=\"FxRate\" /></FieldRefs></Field>"
    }
];

  // ---------------------------------------------------------------- preflight
  const f = await J(base + "/_api/web/lists/getbytitle('" + LIST + "')/fields"
              + "?$select=InternalName,TypeAsString&$top=500");
  if (!f.value || !f.value.length) { console.error("ABORT: read 0 fields."); return; }
  const have = new Map(f.value.map(x => [x.InternalName, x.TypeAsString]));

  const edd = have.get(EDD_INTERNAL);
  if (!edd) {
    console.error("ABORT: '" + EDD_INTERNAL + "' does not exist on " + LIST + ".");
    console.error("  Fx Year reads it and the two price columns read Fx Year.");
    console.error("  Create it as a STORED column first -- a calculated column cannot");
    console.error("  read a column-formatting result.");
    return;
  }
  if (edd === "Calculated") {
    console.error("ABORT: '" + EDD_INTERNAL + "' is a Calculated column.");
    console.error("  It uses TODAY(), which SharePoint evaluates only on write, so it");
    console.error("  freezes at last save. That is the bug this whole port exists past.");
    return;
  }
  console.log("Estimated Delivery Date present, type " + edd + " -- ok\n");

  const dup = FIELDS.filter(x => have.has(x.name));
  if (dup.length) {
    console.error("ABORT: already present: " + dup.map(d => d.name).join(", "));
    console.error("  Delete them first, or this creates duplicates with a 0 suffix --");
    console.error("  the x9 cleanup exists because that already happened once.");
    return;
  }
  for (const x of FIELDS)
    for (const r of x.refs)
      if (!have.has(r) && !FIELDS.some(y => y.name === r))
        { console.error("ABORT: " + x.name + " references missing field " + r); return; }

  console.table(FIELDS.map(x => ({ field: x.name, type: x.rtype, formula: x.formula })));
  if (!APPLY) { console.log("\nDRY RUN -- nothing created. Set APPLY = true."); return; }

  const dg = await (await fetch(base + "/_api/contextinfo", { method:"POST",
    credentials:"include", headers:{Accept:"application/json;odata=nometadata"} })).json();

  const results = [];
  // Sequential on purpose: Fx Rate references Fx Year and the price columns reference
  // both, and SharePoint rejects a FieldRef to a field that does not exist yet.
  for (const x of FIELDS) {
    try {
      const r = await fetch(base + "/_api/web/lists/getbytitle('" + LIST
        + "')/fields/createfieldasxml", {
        method:"POST", credentials:"include",
        headers:{ Accept:"application/json;odata=nometadata",
                  "Content-Type":"application/json;odata=verbose",
                  "X-RequestDigest": dg.FormDigestValue },
        body: JSON.stringify({ parameters: {
          __metadata:{ type:"SP.XmlSchemaFieldCreationInformation" },
          SchemaXml: x.xml, Options: 8 } })
      });
      results.push({ field:x.name, ok:r.ok, status:r.status,
                     error: r.ok ? "" : (await r.text()).slice(0,300) });
      if (!r.ok) break;   // a later field references this one; stop rather than cascade
    } catch (e) { results.push({ field:x.name, ok:false, status:0, error:String(e) }); break; }
  }
  console.table(results);

  // Read back. A 200 is not proof SharePoint stored the ResultType you asked for --
  // it silently accepts and downgrades some combinations.
  const after = await J(base + "/_api/web/lists/getbytitle('" + LIST + "')/fields"
                  + "?$select=InternalName,TypeAsString,OutputType&$top=500");
  const made = (after.value||[]).filter(x => FIELDS.some(y => y.name === x.InternalName));
  console.log("\n--- read back (trust this, not the POST results) ---");
  console.table(made.map(x => ({ field:x.InternalName, type:x.TypeAsString, output:x.OutputType })));
})();
