/* X23 -- READ-ONLY. Emits the Power Fx that fixes the race at its source.

   🔴 GENERATED by scripts/gen_x23_powerfx.py from the live N3 flow definitions.
   Do not hand-edit the MAP; re-run the generator after any mapping change.

   HOW TO RUN
     1. Open, signed in:
        https://ermcopower.sharepoint.com/sites/PioneerPlanificatio/_api/web/currentuser
     2. F12 -> Console. Paste this whole file. Press Enter.
     3. Copy the emitted Power Fx into the order-creation save.

   Writes nothing to SharePoint. It only reads column metadata and prints text.

   WHAT IT FIXES
     The save creates the Model Revision, patches Models, then creates the Order
     -- three parent writes about a second apart, each firing its own sync flow
     -- and only then creates the units one at a time at 4-5s each. So:

       - the Order sync fans out into a child list still being written for
         roughly Qty x 4.5 seconds  ->  THE RACE (order 22169 lost 4 of 10);
       - three flows fan out onto the same rows within one second
         ->  SAVE CONFLICT 400, never retried (22172, 22175).

     Both vanish if the unit is born complete. At the moment it creates each
     unit the app already holds varNewOrder, SelectedModel,
     SelectedModelRevision and SelectedClient -- every value the flows would
     write. One writer, at a moment when no other writer exists.

     It also retires the post-backfill gap: a unit created at any time is right.

   ⚠️ WHY THE NAMES ARE READ AND NOT TYPED
     Power Fx addresses SharePoint by DISPLAY name; the flows use INTERNAL
     names. This repo's docs have named non-existent fields three times
     (`OrdOrderNumber`, `OrdQty`, `Model_Revion_ID`). So the mapping below comes
     from the flow definitions, and the display names are read off the live
     lists right here, by _api/v2.0/.../columns -- the one route that works on
     this tenant (_api/web/lists/.../fields hangs: four 45-second timeouts).

   ⚠️ WHAT THIS DOES NOT DO
     The N3 flows still exist and still handle LATER parent edits, where two of
     them can still collide on one row. The retry scope is still worth adding.
     This takes order creation -- the common path -- off the collision course.
*/
(async () => {
  const base = "https://ermcopower.sharepoint.com/sites/PioneerPlanificatio";
  const OI   = "d6468ec5-c7b5-44a3-8ce0-f81f059b671d";

  const MAP = {
  "Ord": {
    "parent": "Order",
    "list": "6fe35dfe-2b7d-455a-abe3-056abb386733",
    "fk": "OrderNumberId",
    "var": "varNewOrder",
    "fields": [
      {
        "target": "OrdClientDateStatus",
        "targetChoice": true,
        "source": "ClientDateStatus",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdEngineeringRequired",
        "targetChoice": false,
        "source": "EngineeringRequired",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdIndexing",
        "targetChoice": true,
        "source": "Indexing",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdInitialPromisedDate",
        "targetChoice": false,
        "source": "Initial_x0020_Promised_x0020_Dat",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdLDs",
        "targetChoice": false,
        "source": "LDs",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdNewmodeltobecreated",
        "targetChoice": true,
        "source": "New_x0020_model_x0020_to_x0020_b",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdNote",
        "targetChoice": false,
        "source": "Note",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdOrderDate",
        "targetChoice": false,
        "source": "Order_x0020_Date",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdOrderStatus",
        "targetChoice": true,
        "source": "OrderStatus",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdOrderStep",
        "targetChoice": true,
        "source": "Order_x0020_Step",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdOrderType",
        "targetChoice": true,
        "source": "Order_x0020_Type1",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdPO",
        "targetChoice": false,
        "source": "PO",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdPrice",
        "targetChoice": false,
        "source": "Price",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdProvinceState",
        "targetChoice": false,
        "source": "Province_x002F_State",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdSalesNotes",
        "targetChoice": false,
        "source": "SalesNotes",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "OrdWETWETP",
        "targetChoice": true,
        "source": "WET_x002d_WETP",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "OrdOrderFolder",
        "targetChoice": false,
        "source": "Order_x0020_Folder",
        "sourceChoice": false,
        "sourceMulti": false
      }
    ]
  },
  "Mdl": {
    "parent": "Models",
    "list": "b43a5140-0f9d-4ac1-9019-43b897074224",
    "fk": "ModelId",
    "var": "SelectedModel",
    "fields": [
      {
        "target": "MdlEstimatedEffort",
        "targetChoice": false,
        "source": "Estimated_x0020_Effort",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "MdlLatestModelRevision",
        "targetChoice": false,
        "source": "ModelRevision",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "MdlModelID",
        "targetChoice": false,
        "source": "ModelID",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "MdlModificationStatus",
        "targetChoice": true,
        "source": "ModificationStatus",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "MdlParentModel",
        "targetChoice": false,
        "source": "ParentModel",
        "sourceChoice": true,
        "sourceMulti": false
      }
    ]
  },
  "Rev": {
    "parent": "Model Revisions",
    "list": "e2ff8703-b590-4648-b181-9b47cf3883ba",
    "fk": "ModelRevisionId",
    "var": "SelectedModelRevision",
    "fields": [
      {
        "target": "RevCable",
        "targetChoice": false,
        "source": "Cable",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevClientModelCode",
        "targetChoice": false,
        "source": "ModelName",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevCopperLV",
        "targetChoice": false,
        "source": "Copper_x0028_LV_x0029_",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevCoreType",
        "targetChoice": true,
        "source": "Core_x0020_Type",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "RevDuplicateOrder",
        "targetChoice": false,
        "source": "DuplicateOrder",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "RevFamily",
        "targetChoice": true,
        "source": "Family",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "RevForm",
        "targetChoice": false,
        "source": "Form",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevJS",
        "targetChoice": false,
        "source": "JS_x0020__x0023_",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevModelDescription",
        "targetChoice": true,
        "source": "Description",
        "sourceChoice": true,
        "sourceMulti": true
      },
      {
        "target": "RevModelType",
        "targetChoice": true,
        "source": "Model_x0020_Type",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "RevModelRevionID",
        "targetChoice": false,
        "source": "ModelID",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevNotes",
        "targetChoice": false,
        "source": "Notes",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevOilAmount",
        "targetChoice": false,
        "source": "OilAmount",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevOilType",
        "targetChoice": true,
        "source": "Oil_x0020_Type",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "RevOvercoil",
        "targetChoice": false,
        "source": "Overcoil",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevPhases",
        "targetChoice": false,
        "source": "Phases",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevPioneerModelCode",
        "targetChoice": false,
        "source": "Model",
        "sourceChoice": true,
        "sourceMulti": false
      },
      {
        "target": "RevPrimaryVoltage",
        "targetChoice": false,
        "source": "PrimaryVoltage",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevSecondaryVoltage",
        "targetChoice": false,
        "source": "SecondaryVoltage",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevSpecDate",
        "targetChoice": false,
        "source": "Spec_Date",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevSpecID",
        "targetChoice": false,
        "source": "SpecID",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevSpecRevision",
        "targetChoice": false,
        "source": "Spec_Revision",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevWireHV",
        "targetChoice": false,
        "source": "Wire_x0028_HV_x0029_",
        "sourceChoice": false,
        "sourceMulti": false
      },
      {
        "target": "RevkVA",
        "targetChoice": false,
        "source": "kVA_x0020_and_x0020_kV",
        "sourceChoice": false,
        "sourceMulti": false
      }
    ]
  },
  "Cli": {
    "parent": "Clients",
    "list": "3bcf7d97-0862-404d-ab3f-eeaa358c05d8",
    "fk": "ClientId",
    "var": "SelectedClient",
    "fields": [
      {
        "target": "CliLeadTimeWeeks",
        "targetChoice": false,
        "source": "CliLeadTimeWeeks",
        "sourceChoice": false,
        "sourceMulti": false
      }
    ]
  }
};

  const J = async (u) => {
    const r = await fetch(u, { credentials: "include",
      headers: { Accept: "application/json;odata=nometadata" } });
    if (!r.ok) throw new Error(r.status + " " + r.statusText);
    return r.json();
  };
  const cols = async (guid) => {
    const j = await J(base + "/_api/v2.0/sites/root/lists/" + guid + "/columns");
    const by = {};
    for (const c of (j.value || [])) by[c.name] = c;
    return by;
  };

  const target = await cols(OI);
  if (!Object.keys(target).length) { console.error("ABORT: read 0 columns on Order Items."); return; }

  /* A display name containing a quote would break the emitted Power Fx. Power
     Fx escapes a single quote by doubling it. */
  const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

  const lines = { Ord: [], Mdl: [], Rev: [], Cli: [] };
  const problems = [];

  for (const g of Object.keys(MAP)) {
    const m = MAP[g];
    const src = await cols(m.list);
    if (!Object.keys(src).length) { problems.push(g + ": could not read " + m.parent + " columns"); continue; }

    for (const f of m.fields) {
      const t = target[f.target], s = src[f.source];
      if (!t) { problems.push(f.target + " is not a column on Order Items"); continue; }
      if (!s) { problems.push(f.source + " is not a column on " + m.parent
                  + " (target " + f.target + ")"); continue; }

      const ref = m.var + "." + q(s.displayName);
      let expr;

      if (f.sourceMulti) {
        /* MultiChoice source, single-value target. The flow does
           first(...)?['Value']; First(...).Value is the Power Fx equivalent.
           Matching the flow matters more than improving on it -- otherwise
           app-created rows and flow-synced rows disagree. */
        expr = "First(" + ref + ").Value";
      } else if (t.choice) {
        /* A Choice TARGET takes a record. If the source is also a Choice or a
           Lookup it already is one, so pass it straight through. */
        expr = (s.choice || s.lookup) ? ref : "{ Value: " + ref + " }";
      } else if (s.lookup) {
        /* Lookup source into a text target: take the displayed value. This is
           the set x22 silently skipped -- MdlLatestModelRevision,
           MdlParentModel, RevDuplicateOrder, RevPioneerModelCode. */
        expr = ref + ".Value";
      } else if (s.choice) {
        expr = ref + ".Value";
      } else {
        expr = ref;
      }

      lines[g].push({ name: q(t.displayName), expr: expr });
    }
  }

  /* `swap` rewrites a group's source variable for the SA branch, and `guard`
     wraps it so a missing twin writes nothing.

     🔑 THE ZERO-MATCH RULE, and why the guard is not optional. 15 of 390 models
     have an SA twin -- 96% do not. `If()` with no else returns Blank(), so a
     twinless SA unit gets blank Mdl* / Rev*, which is correct and is exactly what
     the existing `Model:` / `'Model Revision':` lines in the save already do.
     Writing the MAIN model's values there instead is the failure the N3 spec's
     zero-match branch exists to prevent. */
  const render = (g, swap, guard) => lines[g].map(l => {
    let e = l.expr;
    if (swap) for (const from of Object.keys(swap))
      e = e.split(from + ".").join(swap[from] + ".").split("(" + from + ")").join("(" + swap[from] + ")");
    if (guard) e = "If(!IsBlank(SelectedSAModel), " + e + ")";
    return "        " + l.name + ": " + e;
  }).join(",\n");

  const block = (groups, swap, guardGroups) => groups
    .map(g => "        // --- " + MAP[g].parent + " (" + lines[g].length + " fields)"
              + ((guardGroups || []).indexOf(g) >= 0 ? ", SA twin, blank when there is none" : "") + " ---\n"
              + render(g, (guardGroups || []).indexOf(g) >= 0 ? swap : null,
                          (guardGroups || []).indexOf(g) >= 0))
    .join(",\n");

  console.log("=== 1. paste into the MAIN unit Patch, after 'Model Revision' ===\n");
  console.log(",\n" + block(["Ord", "Mdl", "Rev", "Cli"]));

  console.log("\n\n=== 2. resolve the SA twin's revision row ===");
  console.log("SelectedSAModel holds the twin MODEL, but its revision is only a lookup, so the");
  console.log("Rev* fields have nothing to read. Add this beside the existing SelectedSAModel");
  console.log("Set(), inside the same If(varNewOrder.SA, ...) block:\n");
  console.log("    Set(");
  console.log("        SelectedSAModelRevision,");
  console.log("        LookUp('Model Revisions', ID = SelectedSAModel.'Latest Model Revision'.Id)");
  console.log("    );");
  console.log("\n    // LookUp on a blank SelectedSAModel returns blank, which the guards below expect.");

  console.log("\n\n=== 3. paste into the SA unit Patch, after 'Model Revision' ===\n");
  console.log(",\n" + block(["Ord", "Mdl", "Rev", "Cli"],
                            { "SelectedModel": "SelectedSAModel",
                              "SelectedModelRevision": "SelectedSAModelRevision" },
                            ["Mdl", "Rev"]));
  console.log("\n        // Ord*/Cli* are order-level and client-level, so an SA unit takes the");
  console.log("        // same values as its non-SA siblings -- unguarded, above.");
  console.log("        // Mdl*/Rev* come from the TWIN and are guarded: 15 of 390 models have one.");

  console.log("\n\n=== check before pasting ===");
  const n = lines.Ord.length + lines.Mdl.length + lines.Rev.length + lines.Cli.length;
  console.log("  fields emitted: Ord " + lines.Ord.length + "  Mdl " + lines.Mdl.length
    + "  Rev " + lines.Rev.length + "  Cli " + lines.Cli.length
    + "   total " + n + " per unit, on both the main and the SA Patch");
  if (problems.length) {
    console.log("  🔴 " + problems.length + " unresolved -- do NOT paste until these are understood:");
    for (const p of problems) console.log("      " + p);
  } else {
    console.log("  ✅ every mapped field resolved to a real column on both sides.");
  }
  console.log("\n  ⚠️ CliLeadTimeWeeks: the Clients sync flow reads `body/CliLeadTimeWeeks`,");
  console.log("     which is its own DESTINATION column name, not a field on Clients. The");
  console.log("     line emitted above uses whatever that resolves to -- if Cli shows 0");
  console.log("     fields or appears in the problem list, that is the bug, not this script.");
  console.log("  ⚠️ Dates: Power Fx sends a date value, not a string. The UTC-midnight trap");
  console.log("     that bit the backfill applies to raw REST writes, not to this path.");
  console.log("  ⚠️ Test on a ONE-unit order first, then a 10-unit one, and re-run");
  console.log("     x19_parent_history_probe.js against it: sibling divergence must be none.");
})();
