// Query: ClientLongLeadTimes
let
    Source = TableOrders,
    AverageIsolation = List.Average(StandardJobTimes[Isolation MOY]),
    AverageBobinage = List.Average(StandardJobTimes[Bobinage MOY]),
    AverageEnrouleur = List.Average(StandardJobTimes[Enrouleur MOY]),
    AverageAssembleur = List.Average(StandardJobTimes[Assembleur MOY]),
    AverageEncuveur = List.Average(StandardJobTimes[Encuveur MOY]),
    AverageEssais = List.Average(StandardJobTimes[Essais MOY]),
    AverageMonteur = List.Average(StandardJobTimes[#"Monteur (MIT)"]),
    AverageSoudeur = List.Average(StandardJobTimes[Soudeur MOY]),
    AverageFinition = List.Average(StandardJobTimes[Finition MOY]),
    AverageTotal = List.Average(StandardJobTimes[Total]),
    #"Merged Match By PO Item" = Table.NestedJoin(Source, {"PO Item #"}, StandardJobTimes, {"Part Number"}, "MatchByPoItem", JoinKind.LeftOuter),
    #"Merged Match By Duplicate Order" = Table.NestedJoin(#"Merged Match By PO Item", {"Duplicate Order"}, StandardJobTimes, {"Part Number"}, "MatchByDuplicateOrder", JoinKind.LeftOuter),
    #"Merged Match By PO Item Dup" = Table.NestedJoin(#"Merged Match By Duplicate Order", {"PO Item #"}, StandardJobTimes, {"#DUP"}, "MatchByPoItemDup", JoinKind.LeftOuter),
    #"Merged Match By Duplicate Order Dup" = Table.NestedJoin(#"Merged Match By PO Item Dup", {"Duplicate Order"}, StandardJobTimes, {"#DUP"}, "MatchByDuplicateOrderDup", JoinKind.LeftOuter),
    #"Merged Match By Client KVA Type" = Table.NestedJoin(#"Merged Match By Duplicate Order Dup", {"Client", "KVA and KV", "Type"}, StandardJobTimes, {"Client", "KVA", "Type"}, "MatchByClientKvaType", JoinKind.LeftOuter),
    #"Expanded MatchByPoItem" = Table.ExpandTableColumn(#"Merged Match By Client KVA Type", "MatchByPoItem", {"Numéro JobScope", "Isolation MOY", "Bobinage MOY", "Enrouleur MOY", "Assembleur MOY", "Encuveur MOY", "Essais MOY", "Monteur (MIT)", "Soudeur MOY", "Finition MOY", "Total"}, {"MatchByPoItem.Numéro JobScope", "MatchByPoItem.Isolation MOY", "MatchByPoItem.Bobinage MOY", "MatchByPoItem.Enrouleur MOY", "MatchByPoItem.Assembleur MOY", "MatchByPoItem.Encuveur MOY", "MatchByPoItem.Essais MOY", "MatchByPoItem.Monteur (MIT)", "MatchByPoItem.Soudeur MOY", "MatchByPoItem.Finition MOY", "MatchByPoItem.Total"}),
    #"Expanded MatchByDuplicateOrder" = Table.ExpandTableColumn(#"Expanded MatchByPoItem", "MatchByDuplicateOrder", {"Numéro JobScope", "Isolation MOY", "Bobinage MOY", "Enrouleur MOY", "Assembleur MOY", "Encuveur MOY", "Essais MOY", "Monteur (MIT)", "Soudeur MOY", "Finition MOY", "Total"}, {"MatchByDuplicateOrder.Numéro JobScope", "MatchByDuplicateOrder.Isolation MOY", "MatchByDuplicateOrder.Bobinage MOY", "MatchByDuplicateOrder.Enrouleur MOY", "MatchByDuplicateOrder.Assembleur MOY", "MatchByDuplicateOrder.Encuveur MOY", "MatchByDuplicateOrder.Essais MOY", "MatchByDuplicateOrder.Monteur (MIT)", "MatchByDuplicateOrder.Soudeur MOY", "MatchByDuplicateOrder.Finition MOY", "MatchByDuplicateOrder.Total"}),
    #"Expanded MatchByPoItemDup" = Table.ExpandTableColumn(#"Expanded MatchByDuplicateOrder", "MatchByPoItemDup", {"Numéro JobScope", "Isolation MOY", "Bobinage MOY", "Enrouleur MOY", "Assembleur MOY", "Encuveur MOY", "Essais MOY", "Monteur (MIT)", "Soudeur MOY", "Finition MOY", "Total"}, {"MatchByPoItemDup.Numéro JobScope", "MatchByPoItemDup.Isolation MOY", "MatchByPoItemDup.Bobinage MOY", "MatchByPoItemDup.Enrouleur MOY", "MatchByPoItemDup.Assembleur MOY", "MatchByPoItemDup.Encuveur MOY", "MatchByPoItemDup.Essais MOY", "MatchByPoItemDup.Monteur (MIT)", "MatchByPoItemDup.Soudeur MOY", "MatchByPoItemDup.Finition MOY", "MatchByPoItemDup.Total"}),
    #"Expanded MatchByDuplicateOrderDup" = Table.ExpandTableColumn(#"Expanded MatchByPoItemDup", "MatchByDuplicateOrderDup", {"Numéro JobScope", "Isolation MOY", "Bobinage MOY", "Enrouleur MOY", "Assembleur MOY", "Encuveur MOY", "Essais MOY", "Monteur (MIT)", "Soudeur MOY", "Finition MOY", "Total"}, {"MatchByDuplicateOrderDup.Numéro JobScope", "MatchByDuplicateOrderDup.Isolation MOY", "MatchByDuplicateOrderDup.Bobinage MOY", "MatchByDuplicateOrderDup.Enrouleur MOY", "MatchByDuplicateOrderDup.Assembleur MOY", "MatchByDuplicateOrderDup.Encuveur MOY", "MatchByDuplicateOrderDup.Essais MOY", "MatchByDuplicateOrderDup.Monteur (MIT)", "MatchByDuplicateOrderDup.Soudeur MOY", "MatchByDuplicateOrderDup.Finition MOY", "MatchByDuplicateOrderDup.Total"}),
    #"Expanded MatchByClientKvaType" = Table.ExpandTableColumn(#"Expanded MatchByDuplicateOrderDup", "MatchByClientKvaType", {"Numéro JobScope", "Isolation MOY", "Bobinage MOY", "Enrouleur MOY", "Assembleur MOY", "Encuveur MOY", "Essais MOY", "Monteur (MIT)", "Soudeur MOY", "Finition MOY", "Total"}, {"MatchByClientKvaType.Numéro JobScope", "MatchByClientKvaType.Isolation MOY", "MatchByClientKvaType.Bobinage MOY", "MatchByClientKvaType.Enrouleur MOY", "MatchByClientKvaType.Assembleur MOY", "MatchByClientKvaType.Encuveur MOY", "MatchByClientKvaType.Essais MOY", "MatchByClientKvaType.Monteur (MIT)", "MatchByClientKvaType.Soudeur MOY", "MatchByClientKvaType.Finition MOY", "MatchByClientKvaType.Total"}),
    #"Added Weighted Isolation" = Table.AddColumn(#"Expanded MatchByClientKvaType", "Isolation MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Isolation MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Isolation MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Isolation MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Isolation MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Isolation MOY"]*[Qty] else AverageIsolation, type number),
    #"Added Weighted Bobinage" = Table.AddColumn(#"Added Weighted Isolation", "Bobinage MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Bobinage MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Bobinage MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Bobinage MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Bobinage MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Bobinage MOY"]*[Qty] else AverageBobinage, type number),
    #"Added Weighted Enrouleur" = Table.AddColumn(#"Added Weighted Bobinage", "Enrouleur MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Enrouleur MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Enrouleur MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Enrouleur MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Enrouleur MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Enrouleur MOY"]*[Qty] else AverageEnrouleur, type number),
    #"Added Weighted Assembleur" = Table.AddColumn(#"Added Weighted Enrouleur", "Assembleur MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Assembleur MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Assembleur MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Assembleur MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Assembleur MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Assembleur MOY"]*[Qty] else AverageAssembleur, type number),
    #"Added Weighted Encuveur" = Table.AddColumn(#"Added Weighted Assembleur", "Encuveur MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Encuveur MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Encuveur MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Encuveur MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Encuveur MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Encuveur MOY"]*[Qty] else AverageEncuveur, type number),
    #"Added Weighted Essais" = Table.AddColumn(#"Added Weighted Encuveur", "Essais MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Essais MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Essais MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Essais MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Essais MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Essais MOY"]*[Qty] else AverageEssais, type number),
    #"Added Weighted Monteur" = Table.AddColumn(#"Added Weighted Essais", "Monteur (MIT)", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Monteur (MIT)"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Monteur (MIT)"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Monteur (MIT)"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Monteur (MIT)"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Monteur (MIT)"]*[Qty] else AverageMonteur, type number),
    #"Added Weighted Soudeur" = Table.AddColumn(#"Added Weighted Monteur", "Soudeur MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Soudeur MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Soudeur MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Soudeur MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Soudeur MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Soudeur MOY"]*[Qty] else AverageSoudeur, type number),
    #"Added Weighted Finition" = Table.AddColumn(#"Added Weighted Soudeur", "Finition MOY", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Finition MOY"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Finition MOY"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Finition MOY"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Finition MOY"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Finition MOY"]*[Qty] else AverageFinition, type number),
    #"Added Weighted Total" = Table.AddColumn(#"Added Weighted Finition", "Total", each if [#"MatchByPoItem.Numéro JobScope"] <> null then [#"MatchByPoItem.Total"]*[Qty] else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then [#"MatchByDuplicateOrder.Total"]*[Qty] else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then [#"MatchByPoItemDup.Total"]*[Qty] else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then [#"MatchByDuplicateOrderDup.Total"]*[Qty] else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then [#"MatchByClientKvaType.Total"]*[Qty] else AverageTotal, type number),
    #"Added Matching Strategy Label" = Table.AddColumn(#"Added Weighted Total", "Matching", each if [#"MatchByPoItem.Numéro JobScope"] <> null then "Part Number-PO Item #" else if [#"MatchByDuplicateOrder.Numéro JobScope"] <> null then "Part Number-Duplicate Order" else if [#"MatchByPoItemDup.Numéro JobScope"] <> null then "#DUP-PO Item #" else if [#"MatchByDuplicateOrderDup.Numéro JobScope"] <> null then "#DUP-Duplicate Order" else if [#"MatchByClientKvaType.Numéro JobScope"] <> null then "Client,KVA,Type" else "No match", type text),
    #"Removed Other Columns" = Table.SelectColumns(#"Added Matching Strategy Label",{"Order", "Client", "KVA and KV", "Phases", "JS #", "Description", "Type", "PO", "Order Date", "Qty", "PO Item #", "Duplicate", "Duplicate Order", "Delivery Date", "Isolation MOY", "Bobinage MOY", "Enrouleur MOY", "Assembleur MOY", "Encuveur MOY", "Essais MOY", "Monteur (MIT)", "Soudeur MOY", "Finition MOY", "Total", "Matching"})
in
    #"Removed Other Columns"