// Query: SharepointListMetaColumns
let
    Source = {"Modified", "Created", "Created_By", "Version", "Attachments", "Edit", "Type", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied", "Label applied by", "Item is a Record", "App Created By", "App Modified By", "Content Type", "ID", "Compliance Asset Id", "Color Tag", "Title", "Created By", "Modified By"}
in
    Source